<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class achievements extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('achievements')->insert([
            ['id_team' => 1, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 13],
            ['id_team' => 1, 'name' => 'FA Cup', 'quantity' => 14],
            ['id_team' => 1, 'name' => 'English League Cup (League Cup/Carabao Cup)', 'quantity' => 2],
            ['id_team' => 1, 'name' => 'FA Community Shield', 'quantity' => 17],
            ['id_team' => 1, 'name' => 'UEFA Cup Winners\' Cup', 'quantity' => 1],
            ['id_team' => 1, 'name' => 'Inter-Cities Fairs Cup', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 7],
            ['id_team' => 2, 'name' => 'FA Cup', 'quantity' => 7],
            ['id_team' => 2, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 5],
            ['id_team' => 2, 'name' => 'FA Community Shield', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'UEFA Champions League', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'UEFA Super Cup', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'UEFA Intertoto Cup', 'quantity' => 1],
            ['id_team' => 3, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 1],
            ['id_team' => 3, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 1],
            ['id_team' => 3, 'name' => 'Football League Trophy (EFL Trophy)', 'quantity' => 1],
            ['id_team' => 4, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 1],
            ['id_team' => 4, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 2],
            ['id_team' => 4, 'name' => 'English Championship (Fourth Division/League Two)', 'quantity' => 3],
            ['id_team' => 4, 'name' => 'London Challenge Cup', 'quantity' => 3],
            ['id_team' => 5, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 2],
            ['id_team' => 5, 'name' => 'English Championship (Fourth Division/League Two)', 'quantity' => 2],
            ['id_team' => 5, 'name' => 'FA Community Shield', 'quantity' => 1], // As Southern League champion
            ['id_team' => 6, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 6],
            ['id_team' => 6, 'name' => 'FA Cup', 'quantity' => 8],
            ['id_team' => 6, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 5],
            ['id_team' => 6, 'name' => 'FA Community Shield', 'quantity' => 4],
            ['id_team' => 6, 'name' => 'UEFA Champions League', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'UEFA Europa League', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'UEFA Cup Winners\' Cup', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'UEFA Super Cup', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'FIFA Club World Cup', 'quantity' => 1],
            ['id_team' => 6, 'name' => 'Full Members Cup', 'quantity' => 2],
            ['id_team' => 7, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 2],
            ['id_team' => 7, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 1],
            ['id_team' => 7, 'name' => 'Full Members Cup', 'quantity' => 1],
            ['id_team' => 7, 'name' => 'FA Cup', 'quantity' => 1], // Assuming the 2024-25 title mentioned in the search
            ['id_team' => 8, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 9],
            ['id_team' => 8, 'name' => 'FA Cup', 'quantity' => 5],
            ['id_team' => 8, 'name' => 'FA Community Shield', 'quantity' => 9],
            ['id_team' => 8, 'name' => 'UEFA Cup Winners\' Cup', 'quantity' => 1],
            ['id_team' => 8, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 1],
            ['id_team' => 9, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 3],
            ['id_team' => 9, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 2],
            ['id_team' => 9, 'name' => 'UEFA Intertoto Cup', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'FA Cup', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'UEFA Cup', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 3],
            ['id_team' => 10, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 2],
            ['id_team' => 10, 'name' => 'Texaco Cup', 'quantity' => 1],
            ['id_team' => 11, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 1],
            ['id_team' => 11, 'name' => 'FA Cup', 'quantity' => 1],
            ['id_team' => 11, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 3],
            ['id_team' => 11, 'name' => 'FA Community Shield', 'quantity' => 2],
            ['id_team' => 11, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 8],
            ['id_team' => 11, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 1],
            ['id_team' => 12, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 19],
            ['id_team' => 12, 'name' => 'FA Cup', 'quantity' => 8],
            ['id_team' => 12, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 10],
            ['id_team' => 12, 'name' => 'FA Community Shield', 'quantity' => 16],
            ['id_team' => 12, 'name' => 'UEFA Champions League', 'quantity' => 6],
            ['id_team' => 12, 'name' => 'UEFA Europa League', 'quantity' => 3],
            ['id_team' => 12, 'name' => 'UEFA Super Cup', 'quantity' => 4],
            ['id_team' => 12, 'name' => 'FIFA Club World Cup', 'quantity' => 1],
            ['id_team' => 13, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 1],
            ['id_team' => 13, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 1],
            ['id_team' => 13, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 2],
            ['id_team' => 13, 'name' => 'English Championship (Fourth Division/League Two)', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 10],
            ['id_team' => 14, 'name' => 'FA Cup', 'quantity' => 8],
            ['id_team' => 14, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 8],
            ['id_team' => 14, 'name' => 'FA Community Shield', 'quantity' => 6],
            ['id_team' => 14, 'name' => 'UEFA Champions League', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'UEFA Cup Winners\' Cup', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'UEFA Super Cup', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'FIFA Club World Cup', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 20],
            ['id_team' => 15, 'name' => 'FA Cup', 'quantity' => 13],
            ['id_team' => 15, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 6],
            ['id_team' => 15, 'name' => 'FA Community Shield', 'quantity' => 21],
            ['id_team' => 15, 'name' => 'UEFA Champions League', 'quantity' => 3],
            ['id_team' => 15, 'name' => 'UEFA Europa League', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'UEFA Cup Winners\' Cup', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'UEFA Super Cup', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'Intercontinental Cup', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'FIFA Club World Cup', 'quantity' => 1],
            ['id_team' => 16, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 4],
            ['id_team' => 16, 'name' => 'FA Cup', 'quantity' => 6],
            ['id_team' => 16, 'name' => 'FA Community Shield', 'quantity' => 1],
            ['id_team' => 16, 'name' => 'Inter-Cities Fairs Cup', 'quantity' => 1],
            ['id_team' => 16, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 4],
            ['id_team' => 17, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 1],
            ['id_team' => 17, 'name' => 'FA Cup', 'quantity' => 2],
            ['id_team' => 17, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 4],
            ['id_team' => 17, 'name' => 'FA Community Shield', 'quantity' => 1],
            ['id_team' => 17, 'name' => 'UEFA Champions League', 'quantity' => 2],
            ['id_team' => 17, 'name' => 'UEFA Super Cup', 'quantity' => 1],
            ['id_team' => 17, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 1],
            ['id_team' => 18, 'name' => 'FA Cup', 'quantity' => 1],
            ['id_team' => 18, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 1],
            ['id_team' => 19, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 2],
            ['id_team' => 19, 'name' => 'FA Cup', 'quantity' => 8],
            ['id_team' => 19, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 4],
            ['id_team' => 19, 'name' => 'FA Community Shield', 'quantity' => 7],
            ['id_team' => 19, 'name' => 'UEFA Cup Winners\' Cup', 'quantity' => 1],
            ['id_team' => 19, 'name' => 'UEFA Cup', 'quantity' => 2],
            ['id_team' => 20, 'name' => 'FA Cup', 'quantity' => 3],
            ['id_team' => 20, 'name' => 'UEFA Cup Winners\' Cup', 'quantity' => 1],
            ['id_team' => 20, 'name' => 'UEFA Europa Conference League', 'quantity' => 1],
            ['id_team' => 20, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 1],
            ['id_team' => 21, 'name' => 'English Championship (First Division/Premier League)', 'quantity' => 3],
            ['id_team' => 21, 'name' => 'FA Cup', 'quantity' => 4],
            ['id_team' => 21, 'name' => 'English League Cup (EFL Cup)', 'quantity' => 2],
            ['id_team' => 21, 'name' => 'FA Community Shield', 'quantity' => 4],
            ['id_team' => 21, 'name' => 'English Championship (Second Division/Championship)', 'quantity' => 4],
            ['id_team' => 21, 'name' => 'English Championship (Third Division/League One)', 'quantity' => 1],
        ]);
    }
}
