<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class achievements extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('achievements')->insert([
            ['id_team' => 1, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 13],
            ['id_team' => 1, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 14],
            ['id_team' => 1, 'name' => 'Copa da Liga Inglesa (League Cup/Carabao Cup)', 'quantity' => 2],
            ['id_team' => 1, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 17],
            ['id_team' => 1, 'name' => 'Recopa Europeia da UEFA (UEFA Cup Winners\' Cup)', 'quantity' => 1],
            ['id_team' => 1, 'name' => 'Taça das Cidades com Feiras (Inter-Cities Fairs Cup)', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 7],
            ['id_team' => 2, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 7],
            ['id_team' => 2, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 5],
            ['id_team' => 2, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'Liga dos Campeões da UEFA', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'Supercopa Europeia', 'quantity' => 1],
            ['id_team' => 2, 'name' => 'Copa Intertoto da UEFA', 'quantity' => 1],
            ['id_team' => 3, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 1],
            ['id_team' => 3, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 1],
            ['id_team' => 3, 'name' => 'Troféu da Football League (EFL Trophy)', 'quantity' => 1],
            ['id_team' => 4, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 1],
            ['id_team' => 4, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 2],
            ['id_team' => 4, 'name' => 'Campeonato Inglês (Quarta Divisão/League Two)', 'quantity' => 3],
            ['id_team' => 4, 'name' => 'London Challenge Cup', 'quantity' => 3],
            ['id_team' => 5, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 2],
            ['id_team' => 5, 'name' => 'Campeonato Inglês (Quarta Divisão/League Two)', 'quantity' => 2],
            ['id_team' => 5, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 1], // Como campeão da Southern League
            ['id_team' => 6, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 6],
            ['id_team' => 6, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 8],
            ['id_team' => 6, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 5],
            ['id_team' => 6, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 4],
            ['id_team' => 6, 'name' => 'Liga dos Campeões da UEFA', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'Liga Europa da UEFA', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'Recopa Europeia da UEFA (UEFA Cup Winners\' Cup)', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'Supercopa da UEFA', 'quantity' => 2],
            ['id_team' => 6, 'name' => 'Copa do Mundo de Clubes da FIFA', 'quantity' => 1],
            ['id_team' => 6, 'name' => 'Copa Full Members', 'quantity' => 2],
            ['id_team' => 7, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 2],
            ['id_team' => 7, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 1],
            ['id_team' => 7, 'name' => 'Copa Full Members', 'quantity' => 1],
            ['id_team' => 7, 'name' => 'FA Cup', 'quantity' => 1], // Assumindo o título de 2024-25 mencionado na busca
            ['id_team' => 8, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 9],
            ['id_team' => 8, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 5],
            ['id_team' => 8, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 9],
            ['id_team' => 8, 'name' => 'Recopa Europeia da UEFA (UEFA Cup Winners\' Cup)', 'quantity' => 1],
            ['id_team' => 8, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 1],
            ['id_team' => 9, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 3],
            ['id_team' => 9, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 2],
            ['id_team' => 9, 'name' => 'Copa Intertoto da UEFA', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'Copa da UEFA (UEFA Cup)', 'quantity' => 1],
            ['id_team' => 10, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 3],
            ['id_team' => 10, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 2],
            ['id_team' => 10, 'name' => 'Texaco Cup', 'quantity' => 1],
            ['id_team' => 11, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 1],
            ['id_team' => 11, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 1],
            ['id_team' => 11, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 3],
            ['id_team' => 11, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 2],
            ['id_team' => 11, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 8],
            ['id_team' => 11, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 1],
            ['id_team' => 12, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 19],
            ['id_team' => 12, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 8],
            ['id_team' => 12, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 10],
            ['id_team' => 12, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 16],
            ['id_team' => 12, 'name' => 'Liga dos Campeões da UEFA', 'quantity' => 6],
            ['id_team' => 12, 'name' => 'Liga Europa da UEFA', 'quantity' => 3],
            ['id_team' => 12, 'name' => 'Supercopa da UEFA', 'quantity' => 4],
            ['id_team' => 12, 'name' => 'Copa do Mundo de Clubes da FIFA', 'quantity' => 1],
            ['id_team' => 13, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 1],
            ['id_team' => 13, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 1],
            ['id_team' => 13, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 2],
            ['id_team' => 13, 'name' => 'Campeonato Inglês (Quarta Divisão/League Two)', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 10],
            ['id_team' => 14, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 8],
            ['id_team' => 14, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 8],
            ['id_team' => 14, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 6],
            ['id_team' => 14, 'name' => 'Liga dos Campeões da UEFA', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'Recopa Europeia da UEFA (UEFA Cup Winners\' Cup)', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'Supercopa da UEFA', 'quantity' => 1],
            ['id_team' => 14, 'name' => 'Copa do Mundo de Clubes da FIFA', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 20],
            ['id_team' => 15, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 13],
            ['id_team' => 15, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 6],
            ['id_team' => 15, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 21],
            ['id_team' => 15, 'name' => 'Liga dos Campeões da UEFA', 'quantity' => 3],
            ['id_team' => 15, 'name' => 'Liga Europa da UEFA', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'Recopa Europeia da UEFA (UEFA Cup Winners\' Cup)', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'Supercopa da UEFA', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'Copa Intercontinental', 'quantity' => 1],
            ['id_team' => 15, 'name' => 'Copa do Mundo de Clubes da FIFA', 'quantity' => 1],
            ['id_team' => 16, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 4],
            ['id_team' => 16, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 6],
            ['id_team' => 16, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 1],
            ['id_team' => 16, 'name' => 'Taça das Cidades com Feiras (Inter-Cities Fairs Cup)', 'quantity' => 1],
            ['id_team' => 16, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 4],
            ['id_team' => 17, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 1],
            ['id_team' => 17, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 2],
            ['id_team' => 17, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 4],
            ['id_team' => 17, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 1],
            ['id_team' => 17, 'name' => 'Liga dos Campeões da UEFA', 'quantity' => 2],
            ['id_team' => 17, 'name' => 'Supercopa da UEFA', 'quantity' => 1],
            ['id_team' => 17, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 1],
            ['id_team' => 18, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 1],
            ['id_team' => 18, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 1],
            ['id_team' => 19, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 2],
            ['id_team' => 19, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 8],
            ['id_team' => 19, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 4],
            ['id_team' => 19, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 7],
            ['id_team' => 19, 'name' => 'Recopa Europeia da UEFA (UEFA Cup Winners\' Cup)', 'quantity' => 1],
            ['id_team' => 19, 'name' => 'Copa da UEFA (UEFA Cup)', 'quantity' => 2],
            ['id_team' => 20, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 3],
            ['id_team' => 20, 'name' => 'Recopa Europeia da UEFA (UEFA Cup Winners\' Cup)', 'quantity' => 1],
            ['id_team' => 20, 'name' => 'Liga Conferência Europa da UEFA', 'quantity' => 1],
            ['id_team' => 20, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 1],
            ['id_team' => 21, 'name' => 'Campeonato Inglês (Primeira Divisão/Premier League)', 'quantity' => 3],
            ['id_team' => 21, 'name' => 'Copa da Inglaterra (FA Cup)', 'quantity' => 4],
            ['id_team' => 21, 'name' => 'Copa da Liga Inglesa (EFL Cup)', 'quantity' => 2],
            ['id_team' => 21, 'name' => 'Supercopa da Inglaterra (Community Shield)', 'quantity' => 4],
            ['id_team' => 21, 'name' => 'Campeonato Inglês (Segunda Divisão/Championship)', 'quantity' => 4],
            ['id_team' => 21, 'name' => 'Campeonato Inglês (Terceira Divisão/League One)', 'quantity' => 1],
        ]);
    }
}
