<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class goals extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('goals')->insert([
                [ 'id_team' => 1, 'goal' => 'Finish in the top 6 of the Premier League.', 'goal_level' => 1, 'goal_ptbr' => 'Terminar entre os 6 primeiros da Premier League.' ],
                [ 'id_team' => 1, 'goal' => 'Advance to at least the FA Cup Round of 16.', 'goal_level' => 1, 'goal_ptbr' => 'Avançar pelo menos para as oitavas de final da FA Cup.' ],
                [ 'id_team' => 1, 'goal' => 'Maintain a positive and united dressing room atmosphere.', 'goal_level' => 1, 'goal_ptbr' => 'Manter uma atmosfera positiva e unida no vestiário.' ],
                [ 'id_team' => 1, 'goal' => 'Secure a spot in European competition (Europa League or Champions League).', 'goal_level' => 2, 'goal_ptbr' => 'Garantir uma vaga em competição europeia (Europa League ou Champions League).' ],
                [ 'id_team' => 1, 'goal' => 'Reach the semi-finals of the League Cup (Carabao Cup).', 'goal_level' => 2, 'goal_ptbr' => 'Chegar às semifinais da Copa da Liga (Carabao Cup).' ],
                [ 'id_team' => 1, 'goal' => 'Reduce the number of injuries in the main squad.', 'goal_level' => 2, 'goal_ptbr' => 'Reduzir o número de lesões no elenco principal.' ],
                [ 'id_team' => 1, 'goal' => 'Compete for the Premier League title until the final rounds.', 'goal_level' => 3, 'goal_ptbr' => 'Disputar o título da Premier League até as rodadas finais.' ],
                [ 'id_team' => 1, 'goal' => 'Win either the FA Cup or the League Cup.', 'goal_level' => 3, 'goal_ptbr' => 'Ganhar a FA Cup ou a Copa da Liga.' ],
                [ 'id_team' => 1, 'goal' => 'Reach the Champions League quarter-finals (if qualified).', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às quartas de final da Champions League (se classificado).' ],
                [ 'id_team' => 1, 'goal' => 'Develop and integrate young academy talents into the first team.', 'goal_level' => 3, 'goal_ptbr' => 'Desenvolver e integrar jovens talentos da base ao time principal.' ],
                [ 'id_team' => 1, 'goal' => 'Finish in the top 3 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 3 primeiros da Premier League.' ],
                [ 'id_team' => 1, 'goal' => 'Reach the Champions League semi-finals (if qualified).', 'goal_level' => 4, 'goal_ptbr' => 'Chegar às semifinais da Champions League (se classificado).' ],
                [ 'id_team' => 1, 'goal' => 'Have the best attack or defense in the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Ter o melhor ataque ou defesa da Premier League.' ],
                [ 'id_team' => 1, 'goal' => 'Win the Premier League title.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar o título da Premier League.' ],
                [ 'id_team' => 1, 'goal' => 'Win the Champions League title.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar o título da Champions League.' ],
                [ 'id_team' => 1, 'goal' => 'Achieve a "double" (Premier League + domestic cup or Champions League).', 'goal_level' => 5, 'goal_ptbr' => 'Conquistar uma "dobradinha" (Premier League + copa nacional ou Champions League).' ],
                [ 'id_team' => 2, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1, 'goal_ptbr' => 'Garantir um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 2, 'goal' => 'Advance to at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Avançar pelo menos para a quarta rodada da FA Cup.' ],
                [ 'id_team' => 2, 'goal' => 'Maintain strong squad cohesion and team spirit.', 'goal_level' => 1, 'goal_ptbr' => 'Manter forte coesão e espírito de equipe no elenco.' ],
                [ 'id_team' => 2, 'goal' => 'Qualify for a European competition (Europa Conference League or Europa League).', 'goal_level' => 2, 'goal_ptbr' => 'Classificar-se para uma competição europeia (Europa Conference League ou Europa League).' ],
                [ 'id_team' => 2, 'goal' => 'Reach the League Cup (Carabao Cup) quarter-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar às quartas de final da Copa da Liga (Carabao Cup).' ],
                [ 'id_team' => 2, 'goal' => 'Improve the home record by losing fewer games at Villa Park.', 'goal_level' => 2, 'goal_ptbr' => 'Melhorar o desempenho em casa, perdendo menos jogos no Villa Park.' ],
                [ 'id_team' => 2, 'goal' => 'Finish in a Europa League qualification spot in the Premier League (6th or 7th).', 'goal_level' => 3, 'goal_ptbr' => 'Terminar em uma vaga de classificação para a Europa League na Premier League (6º ou 7º).' ],
                [ 'id_team' => 2, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 2, 'goal' => 'Progress past the group stage in a European competition.', 'goal_level' => 3, 'goal_ptbr' => 'Avançar da fase de grupos em uma competição europeia.' ],
                [ 'id_team' => 2, 'goal' => 'Successfully integrate key new signings into the starting XI.', 'goal_level' => 3, 'goal_ptbr' => 'Integrar com sucesso as principais novas contratações ao time titular.' ],
                [ 'id_team' => 2, 'goal' => 'Challenge for a Champions League spot in the Premier League (top 5).', 'goal_level' => 4, 'goal_ptbr' => 'Disputar uma vaga na Champions League na Premier League (top 5).' ],
                [ 'id_team' => 2, 'goal' => 'Reach the final of a domestic cup competition.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar à final de uma competição de copa nacional.' ],
                [ 'id_team' => 2, 'goal' => 'Make a deep run (quarter-finals or further) in the Europa League.', 'goal_level' => 4, 'goal_ptbr' => 'Fazer uma campanha profunda (quartas de final ou mais) na Europa League.' ],
                [ 'id_team' => 2, 'goal' => 'Finish in the top 4 of the Premier League.', 'goal_level' => 5, 'goal_ptbr' => 'Terminar entre os 4 primeiros da Premier League.' ],
                [ 'id_team' => 2, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 2, 'goal' => 'Win the Europa League.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar a Europa League.' ],
                [ 'id_team' => 3, 'goal' => 'Avoid relegation from the Premier League by a comfortable margin.', 'goal_level' => 1, 'goal_ptbr' => 'Evitar o rebaixamento da Premier League com uma margem confortável.' ],
                [ 'id_team' => 3, 'goal' => 'Maintain a strong defensive record throughout the season.', 'goal_level' => 1, 'goal_ptbr' => 'Manter um forte histórico defensivo ao longo da temporada.' ],
                [ 'id_team' => 3, 'goal' => 'Secure at least 40 points in the Premier League.', 'goal_level' => 1, 'goal_ptbr' => 'Garantir pelo menos 40 pontos na Premier League.' ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2, 'goal_ptbr' => 'Terminar entre os 15 primeiros da Premier League.' ],
                [ 'id_team' => 3, 'goal' => 'Advance to at least the FA Cup Third Round.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar pelo menos para a terceira rodada da FA Cup.' ],
                [ 'id_team' => 3, 'goal' => 'Improve goal difference from the previous season.', 'goal_level' => 2, 'goal_ptbr' => 'Melhorar o saldo de gols em relação à temporada anterior.' ],
                [ 'id_team' => 3, 'goal' => 'Target a top-half finish in the Premier League (10th-12th).', 'goal_level' => 3, 'goal_ptbr' => 'Almejar um lugar na primeira metade da tabela da Premier League (10º-12º).' ],
                [ 'id_team' => 3, 'goal' => 'Reach the League Cup (Carabao Cup) Fourth Round.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar à quarta rodada da Copa da Liga (Carabao Cup).' ],
                [ 'id_team' => 3, 'goal' => 'Develop and integrate promising young players into the first team squad.', 'goal_level' => 3, 'goal_ptbr' => 'Desenvolver e integrar jovens jogadores promissores ao elenco principal.' ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 8 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 8 primeiros da Premier League.' ],
                [ 'id_team' => 3, 'goal' => 'Reach the quarter-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4, 'goal_ptbr' => 'Chegar às quartas de final de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 3, 'goal' => 'Establish a clear playing style and identity on the pitch.', 'goal_level' => 4, 'goal_ptbr' => 'Estabelecer um estilo de jogo e identidade claros em campo.' ],
                [ 'id_team' => 3, 'goal' => 'Qualify for a European competition (e.g., Europa Conference League).', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para uma competição europeia (ex: Europa Conference League).' ],
                [ 'id_team' => 3, 'goal' => 'Reach the semi-finals of a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Chegar às semifinais de uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 6 of the Premier League.', 'goal_level' => 5, 'goal_ptbr' => 'Terminar entre os 6 primeiros da Premier League.' ],
                [ 'id_team' => 3, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1, 'goal_ptbr' => 'Garantir um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 3, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à quarta rodada da FA Cup.' ],
                [ 'id_team' => 3, 'goal' => 'Maintain a positive financial balance and intelligent recruitment.', 'goal_level' => 1, 'goal_ptbr' => 'Manter um balanço financeiro positivo e recrutamento inteligente.' ],
                [ 'id_team' => 3, 'goal' => 'Improve on last season\'s Premier League position (9th).', 'goal_level' => 2, 'goal_ptbr' => 'Melhorar a posição na Premier League em relação à temporada passada (9º).' ],
                [ 'id_team' => 3, 'goal' => 'Advance to the League Cup quarter-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar para as quartas de final da Copa da Liga.' ],
                [ 'id_team' => 3, 'goal' => 'Establish themselves as a consistent mid-table Premier League side.', 'goal_level' => 2, 'goal_ptbr' => 'Estabelecer-se como um time consistente de meio de tabela da Premier League.' ],
                [ 'id_team' => 3, 'goal' => 'Challenge for a European qualification spot (e.g., Europa Conference League).', 'goal_level' => 3, 'goal_ptbr' => 'Disputar uma vaga em competição europeia (ex: Europa Conference League).' ],
                [ 'id_team' => 3, 'goal' => 'Reach the semi-finals of either the FA Cup or League Cup.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais da FA Cup ou da Copa da Liga.' ],
                [ 'id_team' => 3, 'goal' => 'Develop young talents and increase their market value.', 'goal_level' => 3, 'goal_ptbr' => 'Desenvolver jovens talentos e aumentar seu valor de mercado.' ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 7 primeiros da Premier League.' ],
                [ 'id_team' => 3, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar a uma final de copa nacional.' ],
                [ 'id_team' => 3, 'goal' => 'Achieve a club record Premier League points total.', 'goal_level' => 4, 'goal_ptbr' => 'Alcançar um recorde de pontos do clube na Premier League.' ],
                [ 'id_team' => 3, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para a Europa League.' ],
                [ 'id_team' => 3, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 5 of the Premier League.', 'goal_level' => 5, 'goal_ptbr' => 'Terminar entre os 5 primeiros da Premier League.' ],
                [ 'id_team' => 4, 'goal' => 'Secure Premier League safety comfortably, avoiding any relegation battle.', 'goal_level' => 1, 'goal_ptbr' => 'Garantir a permanência na Premier League confortavelmente, evitando qualquer batalha contra o rebaixamento.' ],
                [ 'id_team' => 4, 'goal' => 'Maintain their strong attacking output and continue scoring freely.', 'goal_level' => 1, 'goal_ptbr' => 'Manter sua forte produção ofensiva e continuar marcando gols livremente.' ],
                [ 'id_team' => 4, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à quarta rodada da FA Cup.' ],
                [ 'id_team' => 4, 'goal' => 'Finish in the top half of the Premier League (10th or higher).', 'goal_level' => 2, 'goal_ptbr' => 'Terminar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 4, 'goal' => 'Progress to the League Cup semi-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar para as semifinais da Copa da Liga.' ],
                [ 'id_team' => 4, 'goal' => 'Improve their home form to match their strong away performance.', 'goal_level' => 2, 'goal_ptbr' => 'Melhorar o desempenho em casa para igualar o forte desempenho fora.' ],
                [ 'id_team' => 4, 'goal' => 'Target a European qualification spot (Europa Conference League).', 'goal_level' => 3, 'goal_ptbr' => 'Almejar uma vaga em competição europeia (Europa Conference League).' ],
                [ 'id_team' => 4, 'goal' => 'Reach the FA Cup quarter-finals or better.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às quartas de final da FA Cup ou melhor.' ],
                [ 'id_team' => 4, 'goal' => 'Develop a more consistent defensive record.', 'goal_level' => 3, 'goal_ptbr' => 'Desenvolver um histórico defensivo mais consistente.' ],
                [ 'id_team' => 4, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 7 primeiros da Premier League.' ],
                [ 'id_team' => 4, 'goal' => 'Reach a major domestic cup final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar a uma grande final de copa nacional.' ],
                [ 'id_team' => 4, 'goal' => 'Have one of the top 5 goalscorers in the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Ter um dos 5 maiores artilheiros da Premier League.' ],
                [ 'id_team' => 4, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para a Europa League.' ],
                [ 'id_team' => 4, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 4, 'goal' => 'Finish in a Champions League qualification spot (top 4).', 'goal_level' => 5, 'goal_ptbr' => 'Terminar em uma vaga de classificação para a Champions League (top 4).' ],
                [ 'id_team' => 5, 'goal' => 'Maintain a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1, 'goal_ptbr' => 'Manter um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 5, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à quarta rodada da FA Cup.' ],
                [ 'id_team' => 5, 'goal' => 'Continue to play attractive, possession-based football.', 'goal_level' => 1, 'goal_ptbr' => 'Continuar a jogar um futebol atraente e de posse de bola.' ],
                [ 'id_team' => 5, 'goal' => 'Improve their Premier League position from last season (8th).', 'goal_level' => 2, 'goal_ptbr' => 'Melhorar a posição na Premier League em relação à temporada passada (8º).' ],
                [ 'id_team' => 5, 'goal' => 'Reach the League Cup quarter-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar às quartas de final da Copa da Liga.' ],
                [ 'id_team' => 5, 'goal' => 'Successfully integrate new tactical approaches under the head coach.', 'goal_level' => 2, 'goal_ptbr' => 'Integrar com sucesso novas abordagens táticas sob o comando do treinador.' ],
                [ 'id_team' => 5, 'goal' => 'Secure a European qualification spot (Europa League or Conference League).', 'goal_level' => 3, 'goal_ptbr' => 'Garantir uma vaga em competição europeia (Europa League ou Conference League).' ],
                [ 'id_team' => 5, 'goal' => 'Reach the semi-finals of either the FA Cup or League Cup.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais da FA Cup ou da Copa da Liga.' ],
                [ 'id_team' => 5, 'goal' => 'Reduce the number of goals conceded compared to the previous season.', 'goal_level' => 3, 'goal_ptbr' => 'Reduzir o número de gols sofridos em comparação com a temporada anterior.' ],
                [ 'id_team' => 5, 'goal' => 'Challenge for a Champions League spot in the Premier League (top 5).', 'goal_level' => 4, 'goal_ptbr' => 'Disputar uma vaga na Champions League na Premier League (top 5).' ],
                [ 'id_team' => 5, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar a uma final de copa nacional.' ],
                [ 'id_team' => 5, 'goal' => 'Make a significant run in a European competition (if qualified).', 'goal_level' => 4, 'goal_ptbr' => 'Fazer uma campanha significativa em uma competição europeia (se classificado).' ],
                [ 'id_team' => 5, 'goal' => 'Qualify for the Champions League.', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para a Champions League.' ],
                [ 'id_team' => 5, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 5, 'goal' => 'Win the Europa League (if qualified).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar a Europa League (se classificado).' ],
                [ 'id_team' => 6, 'goal' => 'Secure a top-four finish in the Premier League to qualify for the Champions League.', 'goal_level' => 1, 'goal_ptbr' => 'Garantir um lugar entre os quatro primeiros na Premier League para se classificar para a Champions League.' ],
                [ 'id_team' => 6, 'goal' => 'Reach at least the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 6, 'goal' => 'Progress past the group stage of the FIFA Club World Cup.', 'goal_level' => 1, 'goal_ptbr' => 'Avançar da fase de grupos da Copa do Mundo de Clubes da FIFA.' ],
                [ 'id_team' => 6, 'goal' => 'Challenge for the Premier League title until the final months.', 'goal_level' => 2, 'goal_ptbr' => 'Disputar o título da Premier League até os meses finais.' ],
                [ 'id_team' => 6, 'goal' => 'Reach the quarter-finals of the Champions League.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar às quartas de final da Champions League.' ],
                [ 'id_team' => 6, 'goal' => 'Win the FIFA Club World Cup.', 'goal_level' => 2, 'goal_ptbr' => 'Ganhar a Copa do Mundo de Clubes da FIFA.' ],
                [ 'id_team' => 6, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 6, 'goal' => 'Reach the semi-finals of the Champions League.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais da Champions League.' ],
                [ 'id_team' => 6, 'goal' => 'Establish a clear and consistent playing identity under Enzo Maresca.', 'goal_level' => 3, 'goal_ptbr' => 'Estabelecer uma identidade de jogo clara e consistente sob o comando de Enzo Maresca.' ],
                [ 'id_team' => 6, 'goal' => 'Finish in the top two of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os dois primeiros da Premier League.' ],
                [ 'id_team' => 6, 'goal' => 'Reach the Champions League final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar à final da Champions League.' ],
                [ 'id_team' => 6, 'goal' => 'Have a player win a major individual award (e.g., PFA Player of the Year).', 'goal_level' => 4, 'goal_ptbr' => 'Ter um jogador ganhando um grande prêmio individual (ex: PFA Player of the Year).' ],
                [ 'id_team' => 6, 'goal' => 'Win the Premier League title.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar o título da Premier League.' ],
                [ 'id_team' => 6, 'goal' => 'Win the Champions League.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar a Champions League.' ],
                [ 'id_team' => 6, 'goal' => 'Achieve a domestic cup and European competition "double".', 'goal_level' => 5, 'goal_ptbr' => 'Conquistar uma "dobradinha" de copa nacional e competição europeia.' ],
                [ 'id_team' => 7, 'goal' => 'Avoid relegation from the Premier League by a significant margin.', 'goal_level' => 1, 'goal_ptbr' => 'Evitar o rebaixamento da Premier League com uma margem significativa.' ],
                [ 'id_team' => 7, 'goal' => 'Progress past the group stage of the UEFA Europa League.', 'goal_level' => 1, 'goal_ptbr' => 'Avançar da fase de grupos da UEFA Europa League.' ],
                [ 'id_team' => 7, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à quarta rodada da FA Cup.' ],
                [ 'id_team' => 7, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 2, 'goal_ptbr' => 'Garantir um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 7, 'goal' => 'Reach the quarter-finals of the UEFA Europa League.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar às quartas de final da UEFA Europa League.' ],
                [ 'id_team' => 7, 'goal' => 'Maintain strong form for Jean-Philippe Mateta and other key attackers.', 'goal_level' => 2, 'goal_ptbr' => 'Manter a boa fase de Jean-Philippe Mateta e outros atacantes chave.' ],
                [ 'id_team' => 7, 'goal' => 'Challenge for a Europa League qualification spot through league position.', 'goal_level' => 3, 'goal_ptbr' => 'Disputar uma vaga de classificação para a Europa League via posição na liga.' ],
                [ 'id_team' => 7, 'goal' => 'Reach the semi-finals of the UEFA Europa League.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais da UEFA Europa League.' ],
                [ 'id_team' => 7, 'goal' => 'Successfully manage squad rotation to compete on multiple fronts.', 'goal_level' => 3, 'goal_ptbr' => 'Gerenciar com sucesso a rotação do elenco para competir em múltiplas frentes.' ],
                [ 'id_team' => 7, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 7 primeiros da Premier League.' ],
                [ 'id_team' => 7, 'goal' => 'Reach the final of the UEFA Europa League.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar à final da UEFA Europa League.' ],
                [ 'id_team' => 7, 'goal' => 'Develop new academy players to bolster the first team.', 'goal_level' => 4, 'goal_ptbr' => 'Desenvolver novos jogadores da base para reforçar o time principal.' ],
                [ 'id_team' => 7, 'goal' => 'Win the UEFA Europa League.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar a UEFA Europa League.' ],
                [ 'id_team' => 7, 'goal' => 'Qualify for the Champions League via league position.', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para a Champions League via posição na liga.' ],
                [ 'id_team' => 7, 'goal' => 'Win a domestic cup again while maintaining strong league form.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma copa nacional novamente enquanto mantém forte desempenho na liga.' ],
                [ 'id_team' => 8, 'goal' => 'Secure Premier League safety without any relegation concerns.', 'goal_level' => 1, 'goal_ptbr' => 'Garantir a permanência na Premier League sem preocupações com rebaixamento.' ],
                [ 'id_team' => 8, 'goal' => 'Successfully transition to the new Hill Dickinson Stadium.', 'goal_level' => 1, 'goal_ptbr' => 'Fazer a transição com sucesso para o novo Hill Dickinson Stadium.' ],
                [ 'id_team' => 8, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à terceira rodada da FA Cup.' ],
                [ 'id_team' => 8, 'goal' => 'Achieve a top-half Premier League finish (10th or higher).', 'goal_level' => 2, 'goal_ptbr' => 'Conquistar um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 8, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar para as quartas de final da Copa da Liga.' ],
                [ 'id_team' => 8, 'goal' => 'Continue to develop young talents like Jarrad Branthwaite.', 'goal_level' => 2, 'goal_ptbr' => 'Continuar a desenvolver jovens talentos como Jarrad Branthwaite.' ],
                [ 'id_team' => 8, 'goal' => 'Challenge for a European qualification spot (e.g., Europa Conference League).', 'goal_level' => 3, 'goal_ptbr' => 'Disputar uma vaga em competição europeia (ex: Europa Conference League).' ],
                [ 'id_team' => 8, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 8, 'goal' => 'Ensure financial stability and a sustainable transfer policy.', 'goal_level' => 3, 'goal_ptbr' => 'Garantir estabilidade financeira e uma política de transferências sustentável.' ],
                [ 'id_team' => 8, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 7 primeiros da Premier League.' ],
                [ 'id_team' => 8, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar a uma final de copa nacional.' ],
                [ 'id_team' => 8, 'goal' => 'Have a striker score 15+ Premier League goals.', 'goal_level' => 4, 'goal_ptbr' => 'Ter um atacante marcando 15+ gols na Premier League.' ],
                [ 'id_team' => 8, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para a Europa League.' ],
                [ 'id_team' => 8, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 8, 'goal' => 'Finish in the top 5 of the Premier League.', 'goal_level' => 5, 'goal_ptbr' => 'Terminar entre os 5 primeiros da Premier League.' ],
                [ 'id_team' => 9, 'goal' => 'Secure Premier League safety without late-season pressure.', 'goal_level' => 1, 'goal_ptbr' => 'Garantir a permanência na Premier League sem pressão no final da temporada.' ],
                [ 'id_team' => 9, 'goal' => 'Successfully open and utilize the new Riverside Stand and Fulham Pier.', 'goal_level' => 1, 'goal_ptbr' => 'Abrir e utilizar com sucesso a nova Tribuna Riverside e o Fulham Pier.' ],
                [ 'id_team' => 9, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à quarta rodada da FA Cup.' ],
                [ 'id_team' => 9, 'goal' => 'Achieve a top-half Premier League finish (10th or higher).', 'goal_level' => 2, 'goal_ptbr' => 'Conquistar um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 9, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar para as quartas de final da Copa da Liga.' ],
                [ 'id_team' => 9, 'goal' => 'Reduce points dropped from winning positions.', 'goal_level' => 2, 'goal_ptbr' => 'Reduzir os pontos perdidos de posições de vitória.' ],
                [ 'id_team' => 9, 'goal' => 'Challenge for a European qualification spot (e.g., Europa Conference League).', 'goal_level' => 3, 'goal_ptbr' => 'Disputar uma vaga em competição europeia (ex: Europa Conference League).' ],
                [ 'id_team' => 9, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 9, 'goal' => 'Secure Marco Silva\'s long-term future at the club.', 'goal_level' => 3, 'goal_ptbr' => 'Garantir o futuro a longo prazo de Marco Silva no clube.' ],
                [ 'id_team' => 9, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 7 primeiros da Premier League.' ],
                [ 'id_team' => 9, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar a uma final de copa nacional.' ],
                [ 'id_team' => 9, 'goal' => 'Consistently beat teams from the lower half of the table.', 'goal_level' => 4, 'goal_ptbr' => 'Vencer consistentemente times da metade inferior da tabela.' ],
                [ 'id_team' => 9, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para a Europa League.' ],
                [ 'id_team' => 9, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 9, 'goal' => 'Achieve a club record Premier League points total (surpassing 54).', 'goal_level' => 5, 'goal_ptbr' => 'Alcançar um recorde de pontos do clube na Premier League (superando 54).' ],
                [ 'id_team' => 10, 'goal' => 'Finish comfortably in the top half of the Championship table.', 'goal_level' => 1, 'goal_ptbr' => 'Terminar confortavelmente na primeira metade da tabela da Championship.' ],
                [ 'id_team' => 10, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à terceira rodada da FA Cup.' ],
                [ 'id_team' => 10, 'goal' => 'Retain key players and build squad depth for a promotion push.', 'goal_level' => 1, 'goal_ptbr' => 'Manter jogadores chave e construir profundidade do elenco para uma disputa por promoção.' ],
                [ 'id_team' => 10, 'goal' => 'Challenge for a play-off spot in the Championship (top 6).', 'goal_level' => 2, 'goal_ptbr' => 'Disputar uma vaga nos play-offs da Championship (top 6).' ],
                [ 'id_team' => 10, 'goal' => 'Progress to the League Cup Third Round.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar para a terceira rodada da Copa da Liga.' ],
                [ 'id_team' => 10, 'goal' => 'Achieve Category One academy status and integrate youth players.', 'goal_level' => 2, 'goal_ptbr' => 'Alcançar o status de academia Categoria Um e integrar jogadores jovens.' ],
                [ 'id_team' => 10, 'goal' => 'Secure a play-off spot and compete for promotion to the Premier League.', 'goal_level' => 3, 'goal_ptbr' => 'Garantir uma vaga nos play-offs e disputar a promoção para a Premier League.' ],
                [ 'id_team' => 10, 'goal' => 'Reach the quarter-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às quartas de final de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 10, 'goal' => 'Have a player score 20+ goals in the Championship.', 'goal_level' => 3, 'goal_ptbr' => 'Ter um jogador marcando 20+ gols na Championship.' ],
                [ 'id_team' => 10, 'goal' => 'Achieve automatic promotion to the Premier League (top 2).', 'goal_level' => 4, 'goal_ptbr' => 'Conquistar a promoção automática para a Premier League (top 2).' ],
                [ 'id_team' => 10, 'goal' => 'Reach a domestic cup semi-final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar a uma semifinal de copa nacional.' ],
                [ 'id_team' => 10, 'goal' => 'Build a squad capable of immediate Premier League survival if promoted.', 'goal_level' => 4, 'goal_ptbr' => 'Construir um elenco capaz de sobreviver imediatamente na Premier League se promovido.' ],
                [ 'id_team' => 10, 'goal' => 'Win the Championship title.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar o título da Championship.' ],
                [ 'id_team' => 10, 'goal' => 'Win a major domestic cup while in the Championship.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional enquanto na Championship.' ],
                [ 'id_team' => 10, 'goal' => 'Achieve promotion and avoid relegation in the immediate Premier League season.', 'goal_level' => 5, 'goal_ptbr' => 'Conquistar a promoção e evitar o rebaixamento na temporada imediata da Premier League.' ],
                [ 'id_team' => 11, 'goal' => 'Avoid relegation from the Premier League.', 'goal_level' => 1, 'goal_ptbr' => 'Evitar o rebaixamento da Premier League.' ],
                [ 'id_team' => 11, 'goal' => 'Successfully navigate any PSR challenges and avoid points deductions.', 'goal_level' => 1, 'goal_ptbr' => 'Navegar com sucesso por quaisquer desafios de PSR e evitar deduções de pontos.' ],
                [ 'id_team' => 11, 'goal' => 'Improve home scoring record and end goal droughts.', 'goal_level' => 1, 'goal_ptbr' => 'Melhorar o histórico de gols em casa e encerrar as secas de gols.' ],
                [ 'id_team' => 11, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2, 'goal_ptbr' => 'Terminar entre os 15 primeiros da Premier League.' ],
                [ 'id_team' => 11, 'goal' => 'Reach the FA Cup Fourth Round.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar à quarta rodada da FA Cup.' ],
                [ 'id_team' => 11, 'goal' => 'Make strategic and effective loan signings to bolster the squad.', 'goal_level' => 2, 'goal_ptbr' => 'Fazer contratações por empréstimo estratégicas e eficazes para reforçar o elenco.' ],
                [ 'id_team' => 11, 'goal' => 'Establish themselves as a consistent mid-table Premier League side (10th-12th).', 'goal_level' => 3, 'goal_ptbr' => 'Estabelecer-se como um time consistente de meio de tabela da Premier League (10º-12º).' ],
                [ 'id_team' => 11, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 3, 'goal_ptbr' => 'Avançar para as quartas de final da Copa da Liga.' ],
                [ 'id_team' => 11, 'goal' => 'Develop a clear long-term strategy for financial sustainability and squad building.', 'goal_level' => 3, 'goal_ptbr' => 'Desenvolver uma estratégia clara de longo prazo para sustentabilidade financeira e construção do elenco.' ],
                [ 'id_team' => 11, 'goal' => 'Challenge for a top-half Premier League finish (8th-10th).', 'goal_level' => 4, 'goal_ptbr' => 'Disputar um lugar na primeira metade da tabela da Premier League (8º-10º).' ],
                [ 'id_team' => 11, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 11, 'goal' => 'Secure the future of key players amidst transfer interest.', 'goal_level' => 4, 'goal_ptbr' => 'Garantir o futuro de jogadores chave em meio ao interesse de transferências.' ],
                [ 'id_team' => 11, 'goal' => 'Qualify for a European competition (e.g., Europa Conference League).', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se para uma competição europeia (ex: Europa Conference League).' ],
                [ 'id_team' => 11, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 11, 'goal' => 'Finish in the top 6 of the Premier League.', 'goal_level' => 5, 'goal_ptbr' => 'Terminar entre os 6 primeiros da Premier League.' ],
                [ 'id_team' => 12, 'goal' => 'Successfully defend the Premier League title or finish in the top two.', 'goal_level' => 1, 'goal_ptbr' => 'Defender com sucesso o título da Premier League ou terminar entre os dois primeiros.' ],
                [ 'id_team' => 12, 'goal' => 'Progress deep into the Champions League knockout stages (quarter-finals or further).', 'goal_level' => 1, 'goal_ptbr' => 'Avançar profundamente nas fases eliminatórias da Champions League (quartas de final ou mais).' ],
                [ 'id_team' => 12, 'goal' => 'Win the FA Community Shield.', 'goal_level' => 1, 'goal_ptbr' => 'Ganhar a FA Community Shield.' ],
                [ 'id_team' => 12, 'goal' => 'Win a domestic cup (FA Cup or League Cup).', 'goal_level' => 2, 'goal_ptbr' => 'Ganhar uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 12, 'goal' => 'Reach the Champions League semi-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar às semifinais da Champions League.' ],
                [ 'id_team' => 12, 'goal' => 'Successfully integrate new signings like Florian Wirtz.', 'goal_level' => 2, 'goal_ptbr' => 'Integrar com sucesso novas contratações como Florian Wirtz.' ],
                [ 'id_team' => 12, 'goal' => 'Win a "double" (Premier League + domestic cup/Champions League).', 'goal_level' => 3, 'goal_ptbr' => 'Ganhar uma "dobradinha" (Premier League + copa nacional/Champions League).' ],
                [ 'id_team' => 12, 'goal' => 'Reach the Champions League final.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar à final da Champions League.' ],
                [ 'id_team' => 12, 'goal' => 'Maintain Mohamed Salah\'s elite goal contribution level.', 'goal_level' => 3, 'goal_ptbr' => 'Manter o nível de contribuição de gols de elite de Mohamed Salah.' ],
                [ 'id_team' => 12, 'goal' => 'Win the Champions League.', 'goal_level' => 4, 'goal_ptbr' => 'Ganhar a Champions League.' ],
                [ 'id_team' => 12, 'goal' => 'Achieve a domestic treble.', 'goal_level' => 4, 'goal_ptbr' => 'Conquistar uma tríplice coroa nacional.' ],
                [ 'id_team' => 12, 'goal' => 'Break the Premier League points record.', 'goal_level' => 4, 'goal_ptbr' => 'Quebrar o recorde de pontos da Premier League.' ],
                [ 'id_team' => 12, 'goal' => 'Win the Premier League and Champions League "double".', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar a Premier League e a Champions League (dobradinha).' ],
                [ 'id_team' => 12, 'goal' => 'Achieve an "Invincible" Premier League season (undefeated).', 'goal_level' => 5, 'goal_ptbr' => 'Conquistar uma temporada "Invencível" na Premier League (invicto).' ],
                [ 'id_team' => 12, 'goal' => 'Establish a new era of sustained dominance under Arne Slot.', 'goal_level' => 5, 'goal_ptbr' => 'Estabelecer uma nova era de domínio sustentado sob Arne Slot.' ],
                [ 'id_team' => 13, 'goal' => 'Consolidate in League One and avoid any relegation concerns.', 'goal_level' => 1, 'goal_ptbr' => 'Consolidar-se na League One e evitar preocupações com rebaixamento.' ],
                [ 'id_team' => 13, 'goal' => 'Reach at least the FA Cup Second Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à segunda rodada da FA Cup.' ],
                [ 'id_team' => 13, 'goal' => 'Rebuild team morale and identity under Matt Bloomfield.', 'goal_level' => 1, 'goal_ptbr' => 'Reconstruir a moral e a identidade da equipe sob Matt Bloomfield.' ],
                [ 'id_team' => 13, 'goal' => 'Finish in the top half of League One.', 'goal_level' => 2, 'goal_ptbr' => 'Terminar na primeira metade da tabela da League One.' ],
                [ 'id_team' => 13, 'goal' => 'Reach the EFL Cup Third Round.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar à terceira rodada da EFL Cup.' ],
                [ 'id_team' => 13, 'goal' => 'Have a strong home record at Kenilworth Road.', 'goal_level' => 2, 'goal_ptbr' => 'Ter um forte histórico em casa no Kenilworth Road.' ],
                [ 'id_team' => 13, 'goal' => 'Challenge for a play-off spot in League One (top 6).', 'goal_level' => 3, 'goal_ptbr' => 'Disputar uma vaga nos play-offs da League One (top 6).' ],
                [ 'id_team' => 13, 'goal' => 'Reach the quarter-finals of the EFL Trophy.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às quartas de final da EFL Trophy.' ],
                [ 'id_team' => 13, 'goal' => 'Identify and develop key players for a future Championship push.', 'goal_level' => 3, 'goal_ptbr' => 'Identificar e desenvolver jogadores chave para uma futura disputa na Championship.' ],
                [ 'id_team' => 13, 'goal' => 'Secure a play-off spot and compete for promotion to the Championship.', 'goal_level' => 4, 'goal_ptbr' => 'Garantir uma vaga nos play-offs e disputar a promoção para a Championship.' ],
                [ 'id_team' => 13, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 13, 'goal' => 'Win League One automatically (top 2).', 'goal_level' => 4, 'goal_ptbr' => 'Ganhar a League One automaticamente (top 2).' ],
                [ 'id_team' => 13, 'goal' => 'Win League One.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar a League One.' ],
                [ 'id_team' => 13, 'goal' => 'Achieve back-to-back promotions to return to the Championship.', 'goal_level' => 5, 'goal_ptbr' => 'Conquistar promoções consecutivas para retornar à Championship.' ],
                [ 'id_team' => 13, 'goal' => 'Win the FA Cup while in League One.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar a FA Cup enquanto na League One.' ],
                [ 'id_team' => 14, 'goal' => 'Secure a top-two finish in the Premier League.', 'goal_level' => 1, 'goal_ptbr' => 'Garantir um lugar entre os dois primeiros na Premier League.' ],
                [ 'id_team' => 14, 'goal' => 'Reach at least the Champions League quarter-finals.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos às quartas de final da Champions League.' ],
                [ 'id_team' => 14, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 1, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 14, 'goal' => 'Win the Premier League title.', 'goal_level' => 2, 'goal_ptbr' => 'Ganhar o título da Premier League.' ],
                [ 'id_team' => 14, 'goal' => 'Reach the Champions League semi-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Chegar às semifinais da Champions League.' ],
                [ 'id_team' => 14, 'goal' => 'Successfully integrate new signings and bounce back from a "transition" year.', 'goal_level' => 2, 'goal_ptbr' => 'Integrar com sucesso novas contratações e se recuperar de um ano de "transição".' ],
                [ 'id_team' => 14, 'goal' => 'Win a domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Ganhar uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 14, 'goal' => 'Reach the Champions League final.', 'goal_level' => 3, 'goal_ptbr' => 'Chegar à final da Champions League.' ],
                [ 'id_team' => 14, 'goal' => 'Re-establish dominance in all domestic competitions.', 'goal_level' => 3, 'goal_ptbr' => 'Restabelecer o domínio em todas as competições nacionais.' ],
                [ 'id_team' => 14, 'goal' => 'Win the Champions League.', 'goal_level' => 4, 'goal_ptbr' => 'Ganhar a Champions League.' ],
                [ 'id_team' => 14, 'goal' => 'Win the Premier League and a domestic cup "double".', 'goal_level' => 4, 'goal_ptbr' => 'Ganhar a Premier League e uma copa nacional (dobradinha).' ],
                [ 'id_team' => 14, 'goal' => 'Recover key players like Rodri to full fitness and form.', 'goal_level' => 4, 'goal_ptbr' => 'Recuperar jogadores chave como Rodri para plena forma física e desempenho.' ],
                [ 'id_team' => 14, 'goal' => 'Win a treble (Premier League, FA Cup, Champions League).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma tríplice coroa (Premier League, FA Cup, Champions League).' ],
                [ 'id_team' => 14, 'goal' => 'Achieve an "Invincible" Premier League season.', 'goal_level' => 5, 'goal_ptbr' => 'Conquistar uma temporada "Invencível" na Premier League.' ],
                [ 'id_team' => 14, 'goal' => 'Win all possible trophies in a single season (Quadruple).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar todos os troféus possíveis em uma única temporada (Quádrupla Coroa).' ],
                [ 'id_team' => 15, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1, 'goal_ptbr' => 'Garantir um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 15, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à quarta rodada da FA Cup.' ],
                [ 'id_team' => 15, 'goal' => 'Stabilize the club under Rúben Amorim and improve team cohesion.', 'goal_level' => 1, 'goal_ptbr' => 'Estabilizar o clube sob Rúben Amorim e melhorar a coesão da equipe.' ],
                [ 'id_team' => 15, 'goal' => 'Qualify for a European competition (Europa League or Conference League).', 'goal_level' => 2, 'goal_ptbr' => 'Classificar-se para uma competição europeia (Europa League ou Conference League).' ],
                [ 'id_team' => 15, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar para as quartas de final da Copa da Liga.' ],
                [ 'id_team' => 15, 'goal' => 'Improve attacking output and defensive solidity.', 'goal_level' => 2, 'goal_ptbr' => 'Melhorar a produção ofensiva e a solidez defensiva.' ],
                [ 'id_team' => 15, 'goal' => 'Challenge for a Champions League qualification spot (top 4).', 'goal_level' => 3, 'goal_ptbr' => 'Disputar uma vaga de classificação para a Champions League (top 4).' ],
                [ 'id_team' => 15, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 15, 'goal' => 'Overhaul the squad with smart, effective transfers.', 'goal_level' => 3, 'goal_ptbr' => 'Reformular o elenco com transferências inteligentes e eficazes.' ],
                [ 'id_team' => 15, 'goal' => 'Finish in the top 4 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 4 primeiros da Premier League.' ],
                [ 'id_team' => 15, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 4, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 15, 'goal' => 'Have a player score 20+ Premier League goals.', 'goal_level' => 4, 'goal_ptbr' => 'Ter um jogador marcando 20+ gols na Premier League.' ],
                [ 'id_team' => 15, 'goal' => 'Win the Premier League title.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar o título da Premier League.' ],
                [ 'id_team' => 15, 'goal' => 'Win a European competition (Europa League or Conference League).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma competição europeia (Europa League ou Conference League).' ],
                [ 'id_team' => 15, 'goal' => 'Re-establish themselves as a consistent challenger for major trophies.', 'goal_level' => 5, 'goal_ptbr' => 'Restabelecer-se como um desafiante consistente por grandes troféus.' ],
                [ 'id_team' => 16, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1, 'goal_ptbr' => 'Garantir um lugar na primeira metade da tabela da Premier League (10º ou superior).' ],
                [ 'id_team' => 16, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à quarta rodada da FA Cup.' ],
                [ 'id_team' => 16, 'goal' => 'Maintain strong squad depth and manage player fitness effectively.', 'goal_level' => 1, 'goal_ptbr' => 'Manter forte profundidade do elenco e gerenciar a forma física dos jogadores de forma eficaz.' ],
                [ 'id_team' => 16, 'goal' => 'Qualify for a European competition (Europa League or Conference League).', 'goal_level' => 2, 'goal_ptbr' => 'Classificar-se para uma competição europeia (Europa League ou Conference League).' ],
                [ 'id_team' => 16, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2, 'goal_ptbr' => 'Avançar para as quartas de final da Copa da Liga.' ],
                [ 'id_team' => 16, 'goal' => 'Consistently perform against top Premier League sides.', 'goal_level' => 2, 'goal_ptbr' => 'Ter um desempenho consistente contra os principais times da Premier League.' ],
                [ 'id_team' => 16, 'goal' => 'Challenge for a Champions League qualification spot (top 4).', 'goal_level' => 3, 'goal_ptbr' => 'Disputar uma vaga de classificação para a Champions League (top 4).' ],
                [ 'id_team' => 16, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3, 'goal_ptbr' => 'Chegar às semifinais de uma copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 16, 'goal' => 'Strengthen the squad with high-quality additions in key areas.', 'goal_level' => 3, 'goal_ptbr' => 'Fortalecer o elenco com adições de alta qualidade em áreas chave.' ],
                [ 'id_team' => 16, 'goal' => 'Finish in the top 4 of the Premier League.', 'goal_level' => 4, 'goal_ptbr' => 'Terminar entre os 4 primeiros da Premier League.' ],
                [ 'id_team' => 16, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4, 'goal_ptbr' => 'Chegar a uma final de copa nacional.' ],
                [ 'id_team' => 16, 'goal' => 'Make a significant run in a European competition (if qualified).', 'goal_level' => 4, 'goal_ptbr' => 'Fazer uma campanha significativa em uma competição europeia (se classificado).' ],
                [ 'id_team' => 16, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar uma grande copa nacional (FA Cup ou Copa da Liga).' ],
                [ 'id_team' => 16, 'goal' => 'Win the Premier League title.', 'goal_level' => 5, 'goal_ptbr' => 'Ganhar o título da Premier League.' ],
                [ 'id_team' => 16, 'goal' => 'Qualify for and progress deep into the Champions League.', 'goal_level' => 5, 'goal_ptbr' => 'Classificar-se e avançar profundamente na Champions League.' ],
                [ 'id_team' => 17, 'goal' => 'Avoid relegation from the Premier League.', 'goal_level' => 1, 'goal_ptbr' => 'Evitar o rebaixamento da Premier League.' ],
                [ 'id_team' => 17, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1, 'goal_ptbr' => 'Chegar pelo menos à terceira rodada da FA Cup.' ],
                [ 'id_team' => 17, 'goal' => 'Maintain financial compliance and avoid further points deductions.', 'goal_level' => 1, 'goal_ptbr' => 'Manter a conformidade financeira e evitar mais deduções de pontos.' ],
                [ 'id_team' => 17, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2, 'goal_ptbr' => 'Terminar entre os 15 primeiros da Premier League.' ],
            ]
        );
    }
}
