<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class goals extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('goals')->insert([
                [ 'id_team' => 1, 'goal' => 'Finish in the top 6 of the Premier League.', 'goal_level' => 1 ],
                [ 'id_team' => 1, 'goal' => 'Advance to at least the FA Cup Round of 16.', 'goal_level' => 1 ],
                [ 'id_team' => 1, 'goal' => 'Maintain a positive and united dressing room atmosphere.', 'goal_level' => 1 ],
                [ 'id_team' => 1, 'goal' => 'Secure a spot in European competition (Europa League or Champions League).', 'goal_level' => 2 ],
                [ 'id_team' => 1, 'goal' => 'Reach the semi-finals of the League Cup (Carabao Cup).', 'goal_level' => 2 ],
                [ 'id_team' => 1, 'goal' => 'Reduce the number of injuries in the main squad.', 'goal_level' => 2 ],
                [ 'id_team' => 1, 'goal' => 'Compete for the Premier League title until the final rounds.', 'goal_level' => 3 ],
                [ 'id_team' => 1, 'goal' => 'Win either the FA Cup or the League Cup.', 'goal_level' => 3 ],
                [ 'id_team' => 1, 'goal' => 'Reach the Champions League quarter-finals (if qualified).', 'goal_level' => 3 ],
                [ 'id_team' => 1, 'goal' => 'Develop and integrate young academy talents into the first team.', 'goal_level' => 3 ],
                [ 'id_team' => 1, 'goal' => 'Finish in the top 3 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 1, 'goal' => 'Reach the Champions League semi-finals (if qualified).', 'goal_level' => 4 ],
                [ 'id_team' => 1, 'goal' => 'Have the best attack or defense in the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 1, 'goal' => 'Win the Premier League title.', 'goal_level' => 5 ],
                [ 'id_team' => 1, 'goal' => 'Win the Champions League title.', 'goal_level' => 5 ],
                [ 'id_team' => 1, 'goal' => 'Achieve a "double" (Premier League + domestic cup or Champions League).', 'goal_level' => 5 ],
                [ 'id_team' => 2, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1 ],
                [ 'id_team' => 2, 'goal' => 'Advance to at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 2, 'goal' => 'Maintain strong squad cohesion and team spirit.', 'goal_level' => 1 ],
                [ 'id_team' => 2, 'goal' => 'Qualify for a European competition (Europa Conference League or Europa League).', 'goal_level' => 2 ],
                [ 'id_team' => 2, 'goal' => 'Reach the League Cup (Carabao Cup) quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 2, 'goal' => 'Improve the home record by losing fewer games at Villa Park.', 'goal_level' => 2 ],
                [ 'id_team' => 2, 'goal' => 'Finish in a Europa League qualification spot in the Premier League (6th or 7th).', 'goal_level' => 3 ],
                [ 'id_team' => 2, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 2, 'goal' => 'Progress past the group stage in a European competition.', 'goal_level' => 3 ],
                [ 'id_team' => 2, 'goal' => 'Successfully integrate key new signings into the starting XI.', 'goal_level' => 3 ],
                [ 'id_team' => 2, 'goal' => 'Challenge for a Champions League spot in the Premier League (top 5).', 'goal_level' => 4 ],
                [ 'id_team' => 2, 'goal' => 'Reach the final of a domestic cup competition.', 'goal_level' => 4 ],
                [ 'id_team' => 2, 'goal' => 'Make a deep run (quarter-finals or further) in the Europa League.', 'goal_level' => 4 ],
                [ 'id_team' => 2, 'goal' => 'Finish in the top 4 of the Premier League.', 'goal_level' => 5 ],
                [ 'id_team' => 2, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 2, 'goal' => 'Win the Europa League.', 'goal_level' => 5 ],
                [ 'id_team' => 3, 'goal' => 'Avoid relegation from the Premier League by a comfortable margin.', 'goal_level' => 1 ],
                [ 'id_team' => 3, 'goal' => 'Maintain a strong defensive record throughout the season.', 'goal_level' => 1 ],
                [ 'id_team' => 3, 'goal' => 'Secure at least 40 points in the Premier League.', 'goal_level' => 1 ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2 ],
                [ 'id_team' => 3, 'goal' => 'Advance to at least the FA Cup Third Round.', 'goal_level' => 2 ],
                [ 'id_team' => 3, 'goal' => 'Improve goal difference from the previous season.', 'goal_level' => 2 ],
                [ 'id_team' => 3, 'goal' => 'Target a top-half finish in the Premier League (10th-12th).', 'goal_level' => 3 ],
                [ 'id_team' => 3, 'goal' => 'Reach the League Cup (Carabao Cup) Fourth Round.', 'goal_level' => 3 ],
                [ 'id_team' => 3, 'goal' => 'Develop and integrate promising young players into the first team squad.', 'goal_level' => 3 ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 8 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 3, 'goal' => 'Reach the quarter-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 3, 'goal' => 'Establish a clear playing style and identity on the pitch.', 'goal_level' => 4 ],
                [ 'id_team' => 3, 'goal' => 'Qualify for a European competition (e.g., Europa Conference League).', 'goal_level' => 5 ],
                [ 'id_team' => 3, 'goal' => 'Reach the semi-finals of a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 6 of the Premier League.', 'goal_level' => 5 ],
                [ 'id_team' => 3, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1 ],
                [ 'id_team' => 3, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 3, 'goal' => 'Maintain a positive financial balance and intelligent recruitment.', 'goal_level' => 1 ],
                [ 'id_team' => 3, 'goal' => 'Improve on last season\'s Premier League position (9th).', 'goal_level' => 2 ],
                [ 'id_team' => 3, 'goal' => 'Advance to the League Cup quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 3, 'goal' => 'Establish themselves as a consistent mid-table Premier League side.', 'goal_level' => 2 ],
                [ 'id_team' => 3, 'goal' => 'Challenge for a European qualification spot (e.g., Europa Conference League).', 'goal_level' => 3 ],
                [ 'id_team' => 3, 'goal' => 'Reach the semi-finals of either the FA Cup or League Cup.', 'goal_level' => 3 ],
                [ 'id_team' => 3, 'goal' => 'Develop young talents and increase their market value.', 'goal_level' => 3 ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 3, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4 ],
                [ 'id_team' => 3, 'goal' => 'Achieve a club record Premier League points total.', 'goal_level' => 4 ],
                [ 'id_team' => 3, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5 ],
                [ 'id_team' => 3, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 3, 'goal' => 'Finish in the top 5 of the Premier League.', 'goal_level' => 5 ],
                [ 'id_team' => 4, 'goal' => 'Secure Premier League safety comfortably, avoiding any relegation battle.', 'goal_level' => 1 ],
                [ 'id_team' => 4, 'goal' => 'Maintain their strong attacking output and continue scoring freely.', 'goal_level' => 1 ],
                [ 'id_team' => 4, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 4, 'goal' => 'Finish in the top half of the Premier League (10th or higher).', 'goal_level' => 2 ],
                [ 'id_team' => 4, 'goal' => 'Progress to the League Cup semi-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 4, 'goal' => 'Improve their home form to match their strong away performance.', 'goal_level' => 2 ],
                [ 'id_team' => 4, 'goal' => 'Target a European qualification spot (Europa Conference League).', 'goal_level' => 3 ],
                [ 'id_team' => 4, 'goal' => 'Reach the FA Cup quarter-finals or better.', 'goal_level' => 3 ],
                [ 'id_team' => 4, 'goal' => 'Develop a more consistent defensive record.', 'goal_level' => 3 ],
                [ 'id_team' => 4, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 4, 'goal' => 'Reach a major domestic cup final.', 'goal_level' => 4 ],
                [ 'id_team' => 4, 'goal' => 'Have one of the top 5 goalscorers in the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 4, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5 ],
                [ 'id_team' => 4, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 4, 'goal' => 'Finish in a Champions League qualification spot (top 4).', 'goal_level' => 5 ],
                [ 'id_team' => 5, 'goal' => 'Maintain a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1 ],
                [ 'id_team' => 5, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 5, 'goal' => 'Continue to play attractive, possession-based football.', 'goal_level' => 1 ],
                [ 'id_team' => 5, 'goal' => 'Improve their Premier League position from last season (8th).', 'goal_level' => 2 ],
                [ 'id_team' => 5, 'goal' => 'Reach the League Cup quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 5, 'goal' => 'Successfully integrate new tactical approaches under the head coach.', 'goal_level' => 2 ],
                [ 'id_team' => 5, 'goal' => 'Secure a European qualification spot (Europa League or Conference League).', 'goal_level' => 3 ],
                [ 'id_team' => 5, 'goal' => 'Reach the semi-finals of either the FA Cup or League Cup.', 'goal_level' => 3 ],
                [ 'id_team' => 5, 'goal' => 'Reduce the number of goals conceded compared to the previous season.', 'goal_level' => 3 ],
                [ 'id_team' => 5, 'goal' => 'Challenge for a Champions League spot in the Premier League (top 5).', 'goal_level' => 4 ],
                [ 'id_team' => 5, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4 ],
                [ 'id_team' => 5, 'goal' => 'Make a significant run in a European competition (if qualified).', 'goal_level' => 4 ],
                [ 'id_team' => 5, 'goal' => 'Qualify for the Champions League.', 'goal_level' => 5 ],
                [ 'id_team' => 5, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 5, 'goal' => 'Win the Europa League (if qualified).', 'goal_level' => 5 ],
                [ 'id_team' => 6, 'goal' => 'Secure a top-four finish in the Premier League to qualify for the Champions League.', 'goal_level' => 1 ],
                [ 'id_team' => 6, 'goal' => 'Reach at least the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 1 ],
                [ 'id_team' => 6, 'goal' => 'Progress past the group stage of the FIFA Club World Cup.', 'goal_level' => 1 ],
                [ 'id_team' => 6, 'goal' => 'Challenge for the Premier League title until the final months.', 'goal_level' => 2 ],
                [ 'id_team' => 6, 'goal' => 'Reach the quarter-finals of the Champions League.', 'goal_level' => 2 ],
                [ 'id_team' => 6, 'goal' => 'Win the FIFA Club World Cup.', 'goal_level' => 2 ],
                [ 'id_team' => 6, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 6, 'goal' => 'Reach the semi-finals of the Champions League.', 'goal_level' => 3 ],
                [ 'id_team' => 6, 'goal' => 'Establish a clear and consistent playing identity under Enzo Maresca.', 'goal_level' => 3 ],
                [ 'id_team' => 6, 'goal' => 'Finish in the top two of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 6, 'goal' => 'Reach the Champions League final.', 'goal_level' => 4 ],
                [ 'id_team' => 6, 'goal' => 'Have a player win a major individual award (e.g., PFA Player of the Year).', 'goal_level' => 4 ],
                [ 'id_team' => 6, 'goal' => 'Win the Premier League title.', 'goal_level' => 5 ],
                [ 'id_team' => 6, 'goal' => 'Win the Champions League.', 'goal_level' => 5 ],
                [ 'id_team' => 6, 'goal' => 'Achieve a domestic cup and European competition "double".', 'goal_level' => 5 ],
                [ 'id_team' => 7, 'goal' => 'Avoid relegation from the Premier League by a significant margin.', 'goal_level' => 1 ],
                [ 'id_team' => 7, 'goal' => 'Progress past the group stage of the UEFA Europa League.', 'goal_level' => 1 ],
                [ 'id_team' => 7, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 7, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 2 ],
                [ 'id_team' => 7, 'goal' => 'Reach the quarter-finals of the UEFA Europa League.', 'goal_level' => 2 ],
                [ 'id_team' => 7, 'goal' => 'Maintain strong form for Jean-Philippe Mateta and other key attackers.', 'goal_level' => 2 ],
                [ 'id_team' => 7, 'goal' => 'Challenge for a Europa League qualification spot through league position.', 'goal_level' => 3 ],
                [ 'id_team' => 7, 'goal' => 'Reach the semi-finals of the UEFA Europa League.', 'goal_level' => 3 ],
                [ 'id_team' => 7, 'goal' => 'Successfully manage squad rotation to compete on multiple fronts.', 'goal_level' => 3 ],
                [ 'id_team' => 7, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 7, 'goal' => 'Reach the final of the UEFA Europa League.', 'goal_level' => 4 ],
                [ 'id_team' => 7, 'goal' => 'Develop new academy players to bolster the first team.', 'goal_level' => 4 ],
                [ 'id_team' => 7, 'goal' => 'Win the UEFA Europa League.', 'goal_level' => 5 ],
                [ 'id_team' => 7, 'goal' => 'Qualify for the Champions League via league position.', 'goal_level' => 5 ],
                [ 'id_team' => 7, 'goal' => 'Win a domestic cup again while maintaining strong league form.', 'goal_level' => 5 ],
                [ 'id_team' => 8, 'goal' => 'Secure Premier League safety without any relegation concerns.', 'goal_level' => 1 ],
                [ 'id_team' => 8, 'goal' => 'Successfully transition to the new Hill Dickinson Stadium.', 'goal_level' => 1 ],
                [ 'id_team' => 8, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1 ],
                [ 'id_team' => 8, 'goal' => 'Achieve a top-half Premier League finish (10th or higher).', 'goal_level' => 2 ],
                [ 'id_team' => 8, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 8, 'goal' => 'Continue to develop young talents like Jarrad Branthwaite.', 'goal_level' => 2 ],
                [ 'id_team' => 8, 'goal' => 'Challenge for a European qualification spot (e.g., Europa Conference League).', 'goal_level' => 3 ],
                [ 'id_team' => 8, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 8, 'goal' => 'Ensure financial stability and a sustainable transfer policy.', 'goal_level' => 3 ],
                [ 'id_team' => 8, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 8, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4 ],
                [ 'id_team' => 8, 'goal' => 'Have a striker score 15+ Premier League goals.', 'goal_level' => 4 ],
                [ 'id_team' => 8, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5 ],
                [ 'id_team' => 8, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 8, 'goal' => 'Finish in the top 5 of the Premier League.', 'goal_level' => 5 ],
                [ 'id_team' => 9, 'goal' => 'Secure Premier League safety without late-season pressure.', 'goal_level' => 1 ],
                [ 'id_team' => 9, 'goal' => 'Successfully open and utilize the new Riverside Stand and Fulham Pier.', 'goal_level' => 1 ],
                [ 'id_team' => 9, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 9, 'goal' => 'Achieve a top-half Premier League finish (10th or higher).', 'goal_level' => 2 ],
                [ 'id_team' => 9, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 9, 'goal' => 'Reduce points dropped from winning positions.', 'goal_level' => 2 ],
                [ 'id_team' => 9, 'goal' => 'Challenge for a European qualification spot (e.g., Europa Conference League).', 'goal_level' => 3 ],
                [ 'id_team' => 9, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 9, 'goal' => 'Secure Marco Silva\'s long-term future at the club.', 'goal_level' => 3 ],
                [ 'id_team' => 9, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 9, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4 ],
                [ 'id_team' => 9, 'goal' => 'Consistently beat teams from the lower half of the table.', 'goal_level' => 4 ],
                [ 'id_team' => 9, 'goal' => 'Qualify for the Europa League.', 'goal_level' => 5 ],
                [ 'id_team' => 9, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 9, 'goal' => 'Achieve a club record Premier League points total (surpassing 54).', 'goal_level' => 5 ],
                [ 'id_team' => 10, 'goal' => 'Finish comfortably in the top half of the Championship table.', 'goal_level' => 1 ],
                [ 'id_team' => 10, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1 ],
                [ 'id_team' => 10, 'goal' => 'Retain key players and build squad depth for a promotion push.', 'goal_level' => 1 ],
                [ 'id_team' => 10, 'goal' => 'Challenge for a play-off spot in the Championship (top 6).', 'goal_level' => 2 ],
                [ 'id_team' => 10, 'goal' => 'Progress to the League Cup Third Round.', 'goal_level' => 2 ],
                [ 'id_team' => 10, 'goal' => 'Achieve Category One academy status and integrate youth players.', 'goal_level' => 2 ],
                [ 'id_team' => 10, 'goal' => 'Secure a play-off spot and compete for promotion to the Premier League.', 'goal_level' => 3 ],
                [ 'id_team' => 10, 'goal' => 'Reach the quarter-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 10, 'goal' => 'Have a player score 20+ goals in the Championship.', 'goal_level' => 3 ],
                [ 'id_team' => 10, 'goal' => 'Achieve automatic promotion to the Premier League (top 2).', 'goal_level' => 4 ],
                [ 'id_team' => 10, 'goal' => 'Reach a domestic cup semi-final.', 'goal_level' => 4 ],
                [ 'id_team' => 10, 'goal' => 'Build a squad capable of immediate Premier League survival if promoted.', 'goal_level' => 4 ],
                [ 'id_team' => 10, 'goal' => 'Win the Championship title.', 'goal_level' => 5 ],
                [ 'id_team' => 10, 'goal' => 'Win a major domestic cup while in the Championship.', 'goal_level' => 5 ], // Very difficult for a Championship side
                [ 'id_team' => 10, 'goal' => 'Achieve promotion and avoid relegation in the immediate Premier League season.', 'goal_level' => 5 ],
                [ 'id_team' => 11, 'goal' => 'Avoid relegation from the Premier League.', 'goal_level' => 1 ],
                [ 'id_team' => 11, 'goal' => 'Successfully navigate any PSR challenges and avoid points deductions.', 'goal_level' => 1 ],
                [ 'id_team' => 11, 'goal' => 'Improve home scoring record and end goal droughts.', 'goal_level' => 1 ],
                [ 'id_team' => 11, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2 ],
                [ 'id_team' => 11, 'goal' => 'Reach the FA Cup Fourth Round.', 'goal_level' => 2 ],
                [ 'id_team' => 11, 'goal' => 'Make strategic and effective loan signings to bolster the squad.', 'goal_level' => 2 ],
                [ 'id_team' => 11, 'goal' => 'Establish themselves as a consistent mid-table Premier League side (10th-12th).', 'goal_level' => 3 ],
                [ 'id_team' => 11, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 3 ],
                [ 'id_team' => 11, 'goal' => 'Develop a clear long-term strategy for financial sustainability and squad building.', 'goal_level' => 3 ],
                [ 'id_team' => 11, 'goal' => 'Challenge for a top-half Premier League finish (8th-10th).', 'goal_level' => 4 ],
                [ 'id_team' => 11, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 11, 'goal' => 'Secure the future of key players amidst transfer interest.', 'goal_level' => 4 ],
                [ 'id_team' => 11, 'goal' => 'Qualify for a European competition (e.g., Europa Conference League).', 'goal_level' => 5 ],
                [ 'id_team' => 11, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 11, 'goal' => 'Finish in the top 6 of the Premier League.', 'goal_level' => 5 ],
                [ 'id_team' => 12, 'goal' => 'Successfully defend the Premier League title or finish in the top two.', 'goal_level' => 1 ],
                [ 'id_team' => 12, 'goal' => 'Progress deep into the Champions League knockout stages (quarter-finals or further).', 'goal_level' => 1 ],
                [ 'id_team' => 12, 'goal' => 'Win the FA Community Shield.', 'goal_level' => 1 ],
                [ 'id_team' => 12, 'goal' => 'Win a domestic cup (FA Cup or League Cup).', 'goal_level' => 2 ],
                [ 'id_team' => 12, 'goal' => 'Reach the Champions League semi-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 12, 'goal' => 'Successfully integrate new signings like Florian Wirtz.', 'goal_level' => 2 ],
                [ 'id_team' => 12, 'goal' => 'Win a "double" (Premier League + domestic cup/Champions League).', 'goal_level' => 3 ],
                [ 'id_team' => 12, 'goal' => 'Reach the Champions League final.', 'goal_level' => 3 ],
                [ 'id_team' => 12, 'goal' => 'Maintain Mohamed Salah\'s elite goal contribution level.', 'goal_level' => 3 ],
                [ 'id_team' => 12, 'goal' => 'Win the Champions League.', 'goal_level' => 4 ],
                [ 'id_team' => 12, 'goal' => 'Achieve a domestic treble.', 'goal_level' => 4 ],
                [ 'id_team' => 12, 'goal' => 'Break the Premier League points record.', 'goal_level' => 4 ],
                [ 'id_team' => 12, 'goal' => 'Win the Premier League and Champions League "double".', 'goal_level' => 5 ],
                [ 'id_team' => 12, 'goal' => 'Achieve an "Invincible" Premier League season (undefeated).', 'goal_level' => 5 ],
                [ 'id_team' => 12, 'goal' => 'Establish a new era of sustained dominance under Arne Slot.', 'goal_level' => 5 ],
                [ 'id_team' => 13, 'goal' => 'Consolidate in League One and avoid any relegation concerns.', 'goal_level' => 1 ],
                [ 'id_team' => 13, 'goal' => 'Reach at least the FA Cup Second Round.', 'goal_level' => 1 ],
                [ 'id_team' => 13, 'goal' => 'Rebuild team morale and identity under Matt Bloomfield.', 'goal_level' => 1 ],
                [ 'id_team' => 13, 'goal' => 'Finish in the top half of League One.', 'goal_level' => 2 ],
                [ 'id_team' => 13, 'goal' => 'Reach the EFL Cup Third Round.', 'goal_level' => 2 ],
                [ 'id_team' => 13, 'goal' => 'Have a strong home record at Kenilworth Road.', 'goal_level' => 2 ],
                [ 'id_team' => 13, 'goal' => 'Challenge for a play-off spot in League One (top 6).', 'goal_level' => 3 ],
                [ 'id_team' => 13, 'goal' => 'Reach the quarter-finals of the EFL Trophy.', 'goal_level' => 3 ],
                [ 'id_team' => 13, 'goal' => 'Identify and develop key players for a future Championship push.', 'goal_level' => 3 ],
                [ 'id_team' => 13, 'goal' => 'Secure a play-off spot and compete for promotion to the Championship.', 'goal_level' => 4 ],
                [ 'id_team' => 13, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 13, 'goal' => 'Win League One automatically (top 2).', 'goal_level' => 4 ],
                [ 'id_team' => 13, 'goal' => 'Win League One.', 'goal_level' => 5 ],
                [ 'id_team' => 13, 'goal' => 'Achieve back-to-back promotions to return to the Championship.', 'goal_level' => 5 ],
                [ 'id_team' => 13, 'goal' => 'Win the FA Cup while in League One.', 'goal_level' => 5 ], // Extremely difficult
                [ 'id_team' => 14, 'goal' => 'Secure a top-two finish in the Premier League.', 'goal_level' => 1 ],
                [ 'id_team' => 14, 'goal' => 'Reach at least the Champions League quarter-finals.', 'goal_level' => 1 ],
                [ 'id_team' => 14, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 1 ],
                [ 'id_team' => 14, 'goal' => 'Win the Premier League title.', 'goal_level' => 2 ],
                [ 'id_team' => 14, 'goal' => 'Reach the Champions League semi-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 14, 'goal' => 'Successfully integrate new signings and bounce back from a "transition" year.', 'goal_level' => 2 ],
                [ 'id_team' => 14, 'goal' => 'Win a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 14, 'goal' => 'Reach the Champions League final.', 'goal_level' => 3 ],
                [ 'id_team' => 14, 'goal' => 'Re-establish dominance in all domestic competitions.', 'goal_level' => 3 ],
                [ 'id_team' => 14, 'goal' => 'Win the Champions League.', 'goal_level' => 4 ],
                [ 'id_team' => 14, 'goal' => 'Win the Premier League and a domestic cup "double".', 'goal_level' => 4 ],
                [ 'id_team' => 14, 'goal' => 'Recover key players like Rodri to full fitness and form.', 'goal_level' => 4 ],
                [ 'id_team' => 14, 'goal' => 'Win a treble (Premier League, FA Cup, Champions League).', 'goal_level' => 5 ],
                [ 'id_team' => 14, 'goal' => 'Achieve an "Invincible" Premier League season.', 'goal_level' => 5 ],
                [ 'id_team' => 14, 'goal' => 'Win all possible trophies in a single season (Quadruple).', 'goal_level' => 5 ],
                [ 'id_team' => 15, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1 ],
                [ 'id_team' => 15, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 15, 'goal' => 'Stabilize the club under Rúben Amorim and improve team cohesion.', 'goal_level' => 1 ],
                [ 'id_team' => 15, 'goal' => 'Qualify for a European competition (Europa League or Conference League).', 'goal_level' => 2 ],
                [ 'id_team' => 15, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 15, 'goal' => 'Improve attacking output and defensive solidity.', 'goal_level' => 2 ],
                [ 'id_team' => 15, 'goal' => 'Challenge for a Champions League qualification spot (top 4).', 'goal_level' => 3 ],
                [ 'id_team' => 15, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 15, 'goal' => 'Overhaul the squad with smart, effective transfers.', 'goal_level' => 3 ],
                [ 'id_team' => 15, 'goal' => 'Finish in the top 4 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 15, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 15, 'goal' => 'Have a player score 20+ Premier League goals.', 'goal_level' => 4 ],
                [ 'id_team' => 15, 'goal' => 'Win the Premier League title.', 'goal_level' => 5 ],
                [ 'id_team' => 15, 'goal' => 'Win a European competition (Europa League or Conference League).', 'goal_level' => 5 ],
                [ 'id_team' => 15, 'goal' => 'Re-establish themselves as a consistent challenger for major trophies.', 'goal_level' => 5 ],
                [ 'id_team' => 16, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1 ],
                [ 'id_team' => 16, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 16, 'goal' => 'Maintain strong squad depth and manage player fitness effectively.', 'goal_level' => 1 ],
                [ 'id_team' => 16, 'goal' => 'Qualify for a European competition (Europa League or Conference League).', 'goal_level' => 2 ],
                [ 'id_team' => 16, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 16, 'goal' => 'Consistently perform against top Premier League sides.', 'goal_level' => 2 ],
                [ 'id_team' => 16, 'goal' => 'Challenge for a Champions League qualification spot (top 4).', 'goal_level' => 3 ],
                [ 'id_team' => 16, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 16, 'goal' => 'Strengthen the squad with high-quality additions in key areas.', 'goal_level' => 3 ],
                [ 'id_team' => 16, 'goal' => 'Finish in the top 4 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 16, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4 ],
                [ 'id_team' => 16, 'goal' => 'Make a significant run in a European competition (if qualified).', 'goal_level' => 4 ],
                [ 'id_team' => 16, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 16, 'goal' => 'Win the Premier League title.', 'goal_level' => 5 ],
                [ 'id_team' => 16, 'goal' => 'Qualify for and progress deep into the Champions League.', 'goal_level' => 5 ],
                [ 'id_team' => 17, 'goal' => 'Avoid relegation from the Premier League.', 'goal_level' => 1 ],
                [ 'id_team' => 17, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1 ],
                [ 'id_team' => 17, 'goal' => 'Maintain financial compliance and avoid further points deductions.', 'goal_level' => 1 ],
                [ 'id_team' => 17, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2 ],
                [ 'id_team' => 17, 'goal' => 'Progress to the League Cup Fourth Round.', 'goal_level' => 2 ],
                [ 'id_team' => 17, 'goal' => 'Improve goal-scoring consistency from key attacking players.', 'goal_level' => 2 ],
                [ 'id_team' => 17, 'goal' => 'Establish themselves as a stable mid-table Premier League side.', 'goal_level' => 3 ],
                [ 'id_team' => 17, 'goal' => 'Reach the quarter-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 17, 'goal' => 'Successfully integrate academy graduates into the senior squad.', 'goal_level' => 3 ],
                [ 'id_team' => 17, 'goal' => 'Challenge for a top-half Premier League finish (10th-12th).', 'goal_level' => 4 ],
                [ 'id_team' => 17, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 17, 'goal' => 'Have a strong defensive record in the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 17, 'goal' => 'Qualify for a European competition (e.g., Europa Conference League).', 'goal_level' => 5 ],
                [ 'id_team' => 17, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 17, 'goal' => 'Finish in the top 8 of the Premier League.', 'goal_level' => 5 ],
                [ 'id_team' => 18, 'goal' => 'Secure Premier League survival and avoid immediate relegation.', 'goal_level' => 1 ],
                [ 'id_team' => 18, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1 ],
                [ 'id_team' => 18, 'goal' => 'Maintain a strong team spirit and unity after promotion.', 'goal_level' => 1 ],
                [ 'id_team' => 18, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2 ],
                [ 'id_team' => 18, 'goal' => 'Progress to the League Cup Fourth Round.', 'goal_level' => 2 ],
                [ 'id_team' => 18, 'goal' => 'Integrate key transfer window signings effectively.', 'goal_level' => 2 ],
                [ 'id_team' => 18, 'goal' => 'Establish themselves as a consistent Premier League side.', 'goal_level' => 3 ],
                [ 'id_team' => 18, 'goal' => 'Reach the quarter-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 18, 'goal' => 'Develop young players from the academy and integrate them.', 'goal_level' => 3 ],
                [ 'id_team' => 18, 'goal' => 'Challenge for a top-half Premier League finish (10th-12th).', 'goal_level' => 4 ],
                [ 'id_team' => 18, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 18, 'goal' => 'Have a player score 10+ Premier League goals.', 'goal_level' => 4 ],
                [ 'id_team' => 18, 'goal' => 'Qualify for a European competition (e.g., Europa Conference League).', 'goal_level' => 5 ],
                [ 'id_team' => 18, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 18, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 5 ],
                [ 'id_team' => 19, 'goal' => 'Secure a top-six finish in the Premier League to qualify for Europe.', 'goal_level' => 1 ],
                [ 'id_team' => 19, 'goal' => 'Reach at least the FA Cup Fifth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 19, 'goal' => 'Maintain attacking fluidity and goal-scoring form.', 'goal_level' => 1 ],
                [ 'id_team' => 19, 'goal' => 'Qualify for the Champions League (top 4).', 'goal_level' => 2 ],
                [ 'id_team' => 19, 'goal' => 'Progress to the League Cup semi-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 19, 'goal' => 'Strengthen the defensive line for more consistency.', 'goal_level' => 2 ],
                [ 'id_team' => 19, 'goal' => 'Challenge for the Premier League title until the later stages of the season.', 'goal_level' => 3 ],
                [ 'id_team' => 19, 'goal' => 'Reach the final of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 19, 'goal' => 'Make a deep run in a European competition (if qualified).', 'goal_level' => 3 ],
                [ 'id_team' => 19, 'goal' => 'Finish in the top 3 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 19, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 19, 'goal' => 'Reach the Champions League semi-finals.', 'goal_level' => 4 ],
                [ 'id_team' => 19, 'goal' => 'Win the Premier League title.', 'goal_level' => 5 ],
                [ 'id_team' => 19, 'goal' => 'Win the Champions League.', 'goal_level' => 5 ],
                [ 'id_team' => 19, 'goal' => 'End the trophy drought with a significant piece of silverware.', 'goal_level' => 5 ],
                [ 'id_team' => 20, 'goal' => 'Secure a top-half finish in the Premier League (10th or higher).', 'goal_level' => 1 ],
                [ 'id_team' => 20, 'goal' => 'Reach at least the FA Cup Fourth Round.', 'goal_level' => 1 ],
                [ 'id_team' => 20, 'goal' => 'Maintain consistency in all competitions.', 'goal_level' => 1 ],
                [ 'id_team' => 20, 'goal' => 'Qualify for a European competition (Europa Conference League or Europa League).', 'goal_level' => 2 ],
                [ 'id_team' => 20, 'goal' => 'Progress to the League Cup quarter-finals.', 'goal_level' => 2 ],
                [ 'id_team' => 20, 'goal' => 'Maximize the impact of key attacking players.', 'goal_level' => 2 ],
                [ 'id_team' => 20, 'goal' => 'Challenge for a Europa League qualification spot through league position.', 'goal_level' => 3 ],
                [ 'id_team' => 20, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 20, 'goal' => 'Manage squad depth effectively to cope with European fixtures.', 'goal_level' => 3 ],
                [ 'id_team' => 20, 'goal' => 'Finish in the top 7 of the Premier League.', 'goal_level' => 4 ],
                [ 'id_team' => 20, 'goal' => 'Reach a domestic cup final.', 'goal_level' => 4 ],
                [ 'id_team' => 20, 'goal' => 'Make a deep run in a European competition (if qualified).', 'goal_level' => 4 ],
                [ 'id_team' => 20, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 20, 'goal' => 'Qualify for the Champions League.', 'goal_level' => 5 ],
                [ 'id_team' => 20, 'goal' => 'Win a European competition (Europa League or Conference League).', 'goal_level' => 5 ],
                [ 'id_team' => 21, 'goal' => 'Secure Premier League survival comfortably.', 'goal_level' => 1 ],
                [ 'id_team' => 21, 'goal' => 'Reach at least the FA Cup Third Round.', 'goal_level' => 1 ],
                [ 'id_team' => 21, 'goal' => 'Develop a more consistent goal-scoring threat.', 'goal_level' => 1 ],
                [ 'id_team' => 21, 'goal' => 'Finish in the top 15 of the Premier League.', 'goal_level' => 2 ],
                [ 'id_team' => 21, 'goal' => 'Progress to the League Cup Fourth Round.', 'goal_level' => 2 ],
                [ 'id_team' => 21, 'goal' => 'Improve defensive stability and reduce individual errors.', 'goal_level' => 2 ],
                [ 'id_team' => 21, 'goal' => 'Establish themselves as a consistent mid-table Premier League side.', 'goal_level' => 3 ],
                [ 'id_team' => 21, 'goal' => 'Reach the quarter-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 3 ],
                [ 'id_team' => 21, 'goal' => 'Successfully integrate new tactical approaches.', 'goal_level' => 3 ],
                [ 'id_team' => 21, 'goal' => 'Challenge for a top-half Premier League finish (10th-12th).', 'goal_level' => 4 ],
                [ 'id_team' => 21, 'goal' => 'Reach the semi-finals of a domestic cup (FA Cup or League Cup).', 'goal_level' => 4 ],
                [ 'id_team' => 21, 'goal' => 'Develop key young players into consistent Premier League performers.', 'goal_level' => 4 ],
                [ 'id_team' => 21, 'goal' => 'Qualify for a European competition (e.g., Europa Conference League).', 'goal_level' => 5 ],
                [ 'id_team' => 21, 'goal' => 'Win a major domestic cup (FA Cup or League Cup).', 'goal_level' => 5 ],
                [ 'id_team' => 21, 'goal' => 'Finish in the top 8 of the Premier League.', 'goal_level' => 5 ]
            ]
        );
    }
}
