<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class records extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('records')->insert([
            ['id_team' => 1, 'name' => 'Most English top-flight titles without defeat (The Invincibles)'],
            ['id_team' => 1, 'name' => 'Most FA Cup wins (14 titles)'],
            ['id_team' => 1, 'name' => 'Longest unbeaten run in English top-flight league matches (49 games)'],
            ['id_team' => 1, 'name' => 'Most consecutive seasons in the English top flight (107 seasons, ongoing as of 2025)'],
            ['id_team' => 1, 'name' => 'Most consecutive Champions League qualifications (19 seasons, 1998-99 to 2016-17)'],
            ['id_team' => 1, 'name' => 'First London club to reach a UEFA Champions League final (2006)'],
            ['id_team' => 1, 'name' => 'First English team to win the FA Cup and League Cup in the same season (1992-93)'],
            ['id_team' => 1, 'name' => 'Only club to receive a Premier League Golden Trophy (for the Invincibles season)'],
            ['id_team' => 1, 'name' => 'Record for the fewest goals conceded in a 38-game Premier League season (15 goals in 2003-04)'],
            ['id_team' => 1, 'name' => 'Highest number of consecutive away league games scored in (29 games, 2013-2014)'],
            ['id_team' => 1, 'name' => 'Most individual Premier League Golden Boot awards won by players from one club (5 different players)'],
            ['id_team' => 1, 'name' => 'Highest attendance for a club match at the Emirates Stadium (60,383)'],
            ['id_team' => 1, 'name' => 'Longest-serving manager in Premier League history (Arsène Wenger, 22 years)'],
            ['id_team' => 1, 'name' => 'Most goals scored by a player for the club (Thierry Henry, 228 goals)'],
            ['id_team' => 1, 'name' => 'Most clean sheets by a goalkeeper for the club (David Seaman, 237 clean sheets)'],
            ['id_team' => 1, 'name' => 'Youngest player to represent the club (Ethan Nwaneri, 15 years, 181 days)'],
            ['id_team' => 2, 'name' => 'Most competitive goals scored by a player (Billy Walker, 244 goals)'],
            ['id_team' => 2, 'name' => 'Record for the longest winning run in the Premier League at Villa Park (15 consecutive home wins, 2023-2024)'],
            ['id_team' => 2, 'name' => 'Only English club to win the European Cup with 11 players from the local area (1982)'],
            ['id_team' => 2, 'name' => 'Record for the most goals in a single season (71 goals in 1930-31 First Division)'],
            ['id_team' => 2, 'name' => 'One of the founding members of the Football League (1888)'],
            ['id_team' => 2, 'name' => 'Most FA Cups won (7 times, joint record among non-Big Six clubs)'],
            ['id_team' => 2, 'name' => 'First English club to win the European Cup after winning the First Division title 20 years earlier.'],
            ['id_team' => 3, 'name' => 'Highest ever league finish (9th in Premier League, 2024-25)'],
            ['id_team' => 3, 'name' => 'Most goals scored by a player (Brett Pitman, 102 league goals)'],
            ['id_team' => 3, 'name' => 'Record for the fastest rise from League Two to Premier League (6 seasons)'],
            ['id_team' => 3, 'name' => 'Largest competitive victory (10-0 vs. Aldershot, 1990)'],
            ['id_team' => 3, 'name' => 'First time reaching the FA Cup Quarter-finals (2020-21 & 2024-25 seasons)'],
            ['id_team' => 3, 'name' => 'Highest transfer fee received (Dominic Solanke to Tottenham, £65m in 2025)'],
            ['id_team' => 3, 'name' => 'Most expensive departure (Dean Huijsen to Real Madrid, £50m in 2025)'],
            ['id_team' => 4, 'name' => 'Highest ever top-flight league finish (5th in First Division, 1935-36)'],
            ['id_team' => 4, 'name' => 'Most competitive goals scored by a player (Jim Towers, 163 goals)'],
            ['id_team' => 4, 'name' => 'Longest unbeaten run in the Premier League (12 games, 2022-23)'],
            ['id_team' => 4, 'name' => 'Highest points tally in the Premier League (59 points, 2022-23)'],
            ['id_team' => 4, 'name' => 'First promotion to the Premier League (2021)'],
            ['id_team' => 4, 'name' => 'Highest attendance at Griffin Park (38,678 vs Leicester City, 1949)'],
            ['id_team' => 5, 'name' => 'Highest ever league finish (6th in Premier League, 2022-23)'],
            ['id_team' => 5, 'name' => 'Most competitive goals scored by a player (Tommy Cook, 123 goals)'],
            ['id_team' => 5, 'name' => 'First time qualifying for European competition (UEFA Europa League, 2023-24)'],
            ['id_team' => 5, 'name' => 'Record points tally in the Premier League (62 points, 2022-23)'],
            ['id_team' => 5, 'name' => 'Longest unbeaten away run in the Premier League (9 games, 2022-23)'],
            ['id_team' => 5, 'name' => 'Highest transfer fee received (Moisés Caicedo to Chelsea, £115m)'],
            ['id_team' => 6, 'name' => 'Most UEFA Champions League titles by a London club (2 titles)'],
            ['id_team' => 6, 'name' => 'Only London club to have won every major UEFA club competition'],
            ['id_team' => 6, 'name' => 'Record for the most Premier League clean sheets in a season (25 in 2004-05)'],
            ['id_team' => 6, 'name' => 'Most competitive goals scored by a player (Frank Lampard, 211 goals)'],
            ['id_team' => 6, 'name' => 'Most points in a Premier League season (95 points in 2004-05)'],
            ['id_team' => 6, 'name' => 'Longest unbeaten home run in Premier League (86 games, 2004-2008)'],
            ['id_team' => 6, 'name' => 'First English club to win the Premier League, FA Cup and League Cup in consecutive seasons.'],
            ['id_team' => 7, 'name' => 'First major trophy won (FA Cup, 2024-25)'],
            ['id_team' => 7, 'name' => 'Highest ever Premier League points total (53 points, 2024-25)'],
            ['id_team' => 7, 'name' => 'Most competitive goals scored by a player (Peter Simpson, 165 goals)'],
            ['id_team' => 7, 'name' => 'Record for longest FA Cup run as a non-league team (Reached 4th Round as Athenian League side, 1906)'],
            ['id_team' => 7, 'name' => 'First qualification for UEFA Europa League (2025-26)'],
            ['id_team' => 7, 'name' => 'Most goals in a single Premier League season by a player (Jean-Philippe Mateta, 17 goals in 2024-25)'],
            ['id_team' => 7, 'name' => 'Highest transfer fee received (Michael Olise to Bayern Munich, £50.8m)'],
            ['id_team' => 8, 'name' => 'Most seasons in the English top flight (121 seasons, as of 2024-25)'],
            ['id_team' => 8, 'name' => 'Most competitive goals scored by a player (Dixie Dean, 383 goals)'],
            ['id_team' => 8, 'name' => 'Highest number of League titles won (9 titles)'],
            ['id_team' => 8, 'name' => 'First English club to play 100 seasons in the top flight'],
            ['id_team' => 8, 'name' => 'Highest attendance for a league match at Goodison Park (78,299 vs Liverpool, 1948)'],
            ['id_team' => 8, 'name' => 'Longest unbroken period in the top flight (from 1954 to present)'],
            ['id_team' => 8, 'name' => 'Player of the Year at 35 (Idrissa Gueye, 2024-25 season)'],
            ['id_team' => 9, 'name' => 'Highest ever Premier League points total (54 points, 2024-25)'],
            ['id_team' => 9, 'name' => 'Most competitive goals scored by a player (Gordon Davies, 178 goals)'],
            ['id_team' => 9, 'name' => 'Longest-serving London professional club (founded 1879)'],
            ['id_team' => 9, 'name' => 'Record for most league draws in a season (18 draws in 2002-03)'],
            ['id_team' => 9, 'name' => 'Only English club to have reached the UEFA Europa League final while being relegated to the Championship in the same decade.'],
            ['id_team' => 9, 'name' => 'Record for most points dropped from winning positions in Premier League (28 points, 2024-25)'],
            ['id_team' => 10, 'name' => 'Only club to win the FA Cup and UEFA Cup, and finish in the top two divisions without ever winning the top division until 1962.'],
            ['id_team' => 10, 'name' => 'Most competitive goals scored by a player (Ray Crawford, 171 goals)'],
            ['id_team' => 10, 'name' => 'Record for most promotions to the Premier League from the Championship (3 times, most recently 2024)'],
            ['id_team' => 10, 'name' => 'Only club to win the First Division title in their first season after promotion (1961-62)'],
            ['id_team' => 10, 'name' => 'Only British club never to have been relegated below the third tier of English football.'],
            ['id_team' => 11, 'name' => 'Highest odds Premier League title winner (5000/1 in 2015-16)'],
            ['id_team' => 11, 'name' => 'Most competitive goals scored by a player (Arthur Chandler, 273 goals)'],
            ['id_team' => 11, 'name' => 'First club to win the Premier League under a non-British manager (Claudio Ranieri)'],
            ['id_team' => 11, 'name' => 'Record for the longest consecutive home games without scoring (6 games, 2024-25)'],
            ['id_team' => 11, 'name' => 'Highest transfer fee received (Harry Maguire to Manchester United, £80m)'],
            ['id_team' => 11, 'name' => 'First club to win the FA Cup for the first time after 4 previous final defeats (2021)'],
            ['id_team' => 12, 'name' => 'Most League Cups won (10 titles)'],
            ['id_team' => 12, 'name' => 'Most European Cup/Champions League titles won by an English club (6 titles)'],
            ['id_team' => 12, 'name' => 'Most competitive goals scored by a player (Ian Rush, 346 goals)'],
            ['id_team' => 12, 'name' => 'Record for most points in a Premier League season without winning the title (97 points in 2018-19)'],
            ['id_team' => 12, 'name' => 'Longest unbeaten home league run (68 games, 2017-2021)'],
            ['id_team' => 12, 'name' => 'First English club to win the treble of League, League Cup and European Cup in a single season (1983-84)'],
            ['id_team' => 12, 'name' => 'Most consecutive penalty shootout wins (5, from 2022 to 2024)'],
            ['id_team' => 13, 'name' => 'Only club to go from non-league to Premier League (2014-2023)'],
            ['id_team' => 13, 'name' => 'Most competitive goals scored by a player (Joe Payne, 143 goals)'],
            ['id_team' => 13, 'name' => 'First club to win the League Cup on an artificial pitch (1988)'],
            ['id_team' => 13, 'name' => 'Record for back-to-back relegations from Premier League to League One (2024-2025)'],
            ['id_team' => 13, 'name' => 'First club to be in the top flight, then non-league, and then back to the top flight.'],
            ['id_team' => 14, 'name' => 'Most Premier League titles won in a row (4 titles, 2020-2024)'],
            ['id_team' => 14, 'name' => 'Most competitive goals scored by a player (Sergio Agüero, 260 goals)'],
            ['id_team' => 14, 'name' => 'Record for most points in a Premier League season (100 points in 2017-18)'],
            ['id_team' => 14, 'name' => 'Most goals scored in a Premier League season (106 goals in 2017-18)'],
            ['id_team' => 14, 'name' => 'First English club to achieve the domestic treble (2018-19)'],
            ['id_team' => 14, 'name' => 'Fastest goal in a Champions League final (Ilkay Gündogan, 12 seconds in 2023)'],
            ['id_team' => 14, 'name' => 'Most consecutive away league wins (12 games, 2020-21)'],
            ['id_team' => 15, 'name' => 'Most English top-flight League titles (20 titles)'],
            ['id_team' => 15, 'name' => 'Most FA Community Shields won (21 titles)'],
            ['id_team' => 15, 'name' => 'Most competitive goals scored by a player (Wayne Rooney, 253 goals)'],
            ['id_team' => 15, 'name' => 'First English club to win the European Cup (1968)'],
            ['id_team' => 15, 'name' => 'Record for highest average attendance in Premier League history'],
            ['id_team' => 15, 'name' => 'Only English club to win the Treble (Premier League, FA Cup, Champions League in 1998-99)'],
            ['id_team' => 15, 'name' => 'Most FA Cup wins (13 titles)'],
            ['id_team' => 15, 'name' => 'Lowest Premier League points total (59 points in 2024-25)'],
            ['id_team' => 15, 'name' => 'Most league losses in a Premier League season (15 losses in 2024-25)'],
            ['id_team' => 16, 'name' => 'Most competitive goals scored by a player (Alan Shearer, 206 goals)'],
            ['id_team' => 16, 'name' => 'Highest Premier League finish (2nd, 1995-96 and 1996-97)'],
            ['id_team' => 16, 'name' => 'Longest unbeaten run in the Premier League (14 games, 2022-23)'],
            ['id_team' => 16, 'name' => 'Record for most consecutive Premier League victories (9 wins, 2001-02)'],
            ['id_team' => 16, 'name' => 'Largest home attendance (68,386 vs Chelsea, 1930)'],
            ['id_team' => 17, 'name' => 'Only club to win the European Cup more times than their domestic league title (2 European Cups, 1 League title)'],
            ['id_team' => 17, 'name' => 'Most competitive goals scored by a player (Arthur Capes, 104 goals)'],
            ['id_team' => 17, 'name' => 'Record for the longest unbeaten league run in English football (42 games, 1978)'],
            ['id_team' => 17, 'name' => 'First club to win the European Cup after being promoted to the top division (1979)'],
            ['id_team' => 17, 'name' => 'Most consecutive League Cup wins (2, 1978 and 1979)'],
            ['id_team' => 18, 'name' => 'Most competitive goals scored by a player (Mick Channon, 185 goals)'],
            ['id_team' => 18, 'name' => 'Only club to have won the FA Cup while outside the top flight (1976)'],
            ['id_team' => 18, 'name' => 'Record for most players produced by its academy to play for the England senior team'],
            ['id_team' => 18, 'name' => 'Highest Premier League finish (6th, 2015-16)'],
            ['id_team' => 18, 'name' => 'Record for the largest margin of victory in a Premier League game (9-0 vs Leicester City, 2019, and vs Manchester United, 2021)'],
            ['id_team' => 19, 'name' => 'First British club to win a European trophy (European Cup Winners\' Cup, 1963)'],
            ['id_team' => 19, 'name' => 'First club in the 20th century to achieve the League and FA Cup Double (1960-61)'],
            ['id_team' => 19, 'name' => 'Most competitive goals scored by a player (Harry Kane, 280 goals)'],
            ['id_team' => 19, 'name' => 'Most League Cups won by any club (4 titles, joint record)'],
            ['id_team' => 19, 'name' => 'Highest attendance at their new stadium (62,850 vs Arsenal, 2023)'],
            ['id_team' => 19, 'name' => 'Most consecutive seasons scoring in the Premier League (all 33 seasons, ongoing)'],
            ['id_team' => 20, 'name' => 'Most competitive goals scored by a player (Vic Watson, 326 goals)'],
            ['id_team' => 20, 'name' => 'Only English club to win the UEFA Europa Conference League (2023)'],
            ['id_team' => 20, 'name' => 'Record for most FA Cup wins without winning the league (3 titles)'],
            ['id_team' => 20, 'name' => 'Highest Premier League finish (5th, 1998-99 and 2020-21)'],
            ['id_team' => 20, 'name' => 'Most consecutive games without a draw in the Premier League (19 games, 2003-04)'],
            ['id_team' => 21, 'name' => 'Most competitive goals scored by a player (Steve Bull, 306 goals)'],
            ['id_team' => 21, 'name' => 'First club to play in the European Cup (1954-55)'],
            ['id_team' => 21, 'name' => 'Most League titles won by a non-London club (3 titles, joint record)'],
            ['id_team' => 21, 'name' => 'Longest unbeaten home run in the Premier League (11 games, 2019)'],
            ['id_team' => 21, 'name' => 'Record for the highest number of points in the Championship (103 points, 2017-18)']
        ]);
    }
}
