<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class records extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('records')->insert([
            ['id_team' => 1, 'name' => 'Most English top-flight titles without defeat (The Invincibles)', 'name_ptbr' => 'Mais títulos da primeira divisão inglesa sem derrota (Os Invencíveis)'],
            ['id_team' => 1, 'name' => 'Most FA Cup wins (14 titles)', 'name_ptbr' => 'Mais vitórias na FA Cup (14 títulos)'],
            ['id_team' => 1, 'name' => 'Longest unbeaten run in English top-flight league matches (49 games)', 'name_ptbr' => 'Maior sequência invicta em jogos da primeira divisão inglesa (49 jogos)'],
            ['id_team' => 1, 'name' => 'Most consecutive seasons in the English top flight (107 seasons, ongoing as of 2025)', 'name_ptbr' => 'Mais temporadas consecutivas na primeira divisão inglesa (107 temporadas, em andamento a partir de 2025)'],
            ['id_team' => 1, 'name' => 'Most consecutive Champions League qualifications (19 seasons, 1998-99 to 2016-17)', 'name_ptbr' => 'Mais classificações consecutivas para a Champions League (19 temporadas, de 1998-99 a 2016-17)'],
            ['id_team' => 1, 'name' => 'First London club to reach a UEFA Champions League final (2006)', 'name_ptbr' => 'Primeiro clube de Londres a chegar a uma final da UEFA Champions League (2006)'],
            ['id_team' => 1, 'name' => 'First English team to win the FA Cup and League Cup in the same season (1992-93)', 'name_ptbr' => 'Primeiro time inglês a vencer a FA Cup e a Copa da Liga na mesma temporada (1992-93)'],
            ['id_team' => 1, 'name' => 'Only club to receive a Premier League Golden Trophy (for the Invincibles season)', 'name_ptbr' => 'Único clube a receber um Troféu de Ouro da Premier League (pela temporada dos Invencíveis)'],
            ['id_team' => 1, 'name' => 'Record for the fewest goals conceded in a 38-game Premier League season (15 goals in 2003-04)', 'name_ptbr' => 'Recorde de menos gols sofridos em uma temporada de 38 jogos da Premier League (15 gols em 2003-04)'],
            ['id_team' => 1, 'name' => 'Highest number of consecutive away league games scored in (29 games, 2013-2014)', 'name_ptbr' => 'Maior número de jogos consecutivos fora de casa com gols (29 jogos, 2013-2014)'],
            ['id_team' => 1, 'name' => 'Most individual Premier League Golden Boot awards won by players from one club (5 different players)', 'name_ptbr' => 'Mais prêmios Chuteira de Ouro da Premier League ganhos por jogadores de um mesmo clube (5 jogadores diferentes)'],
            ['id_team' => 1, 'name' => 'Highest attendance for a club match at the Emirates Stadium (60,383)', 'name_ptbr' => 'Maior público em uma partida de clube no Emirates Stadium (60.383)'],
            ['id_team' => 1, 'name' => 'Longest-serving manager in Premier League history (Arsène Wenger, 22 years)', 'name_ptbr' => 'Treinador com mais tempo de serviço na história da Premier League (Arsène Wenger, 22 anos)'],
            ['id_team' => 1, 'name' => 'Most goals scored by a player for the club (Thierry Henry, 228 goals)', 'name_ptbr' => 'Mais gols marcados por um jogador pelo clube (Thierry Henry, 228 gols)'],
            ['id_team' => 1, 'name' => 'Most clean sheets by a goalkeeper for the club (David Seaman, 237 clean sheets)', 'name_ptbr' => 'Mais jogos sem sofrer gols por um goleiro pelo clube (David Seaman, 237 jogos sem sofrer gols)'],
            ['id_team' => 1, 'name' => 'Youngest player to represent the club (Ethan Nwaneri, 15 years, 181 days)', 'name_ptbr' => 'Jogador mais jovem a representar o clube (Ethan Nwaneri, 15 anos, 181 dias)'],
            ['id_team' => 2, 'name' => 'Most competitive goals scored by a player (Billy Walker, 244 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Billy Walker, 244 gols)'],
            ['id_team' => 2, 'name' => 'Record for the longest winning run in the Premier League at Villa Park (15 consecutive home wins, 2023-2024)', 'name_ptbr' => 'Recorde de maior sequência de vitórias na Premier League em Villa Park (15 vitórias consecutivas em casa, 2023-2024)'],
            ['id_team' => 2, 'name' => 'Only English club to win the European Cup with 11 players from the local area (1982)', 'name_ptbr' => 'Único clube inglês a vencer a Copa dos Campeões com 11 jogadores da área local (1982)'],
            ['id_team' => 2, 'name' => 'Record for the most goals in a single season (71 goals in 1930-31 First Division)', 'name_ptbr' => 'Recorde de mais gols em uma única temporada (71 gols na Primeira Divisão de 1930-31)'],
            ['id_team' => 2, 'name' => 'One of the founding members of the Football League (1888)', 'name_ptbr' => 'Um dos membros fundadores da Football League (1888)'],
            ['id_team' => 2, 'name' => 'Most FA Cups won (7 times, joint record among non-Big Six clubs)', 'name_ptbr' => 'Mais FA Cups vencidas (7 vezes, recorde conjunto entre clubes fora do Big Six)'],
            ['id_team' => 2, 'name' => 'First English club to win the European Cup after winning the First Division title 20 years earlier.', 'name_ptbr' => 'Primeiro clube inglês a vencer a Copa dos Campeões após vencer o título da Primeira Divisão 20 anos antes.'],
            ['id_team' => 3, 'name' => 'Highest ever league finish (9th in Premier League, 2024-25)', 'name_ptbr' => 'Melhor colocação na liga (9º na Premier League, 2024-25)'],
            ['id_team' => 3, 'name' => 'Most goals scored by a player (Brett Pitman, 102 league goals)', 'name_ptbr' => 'Mais gols marcados por um jogador (Brett Pitman, 102 gols na liga)'],
            ['id_team' => 3, 'name' => 'Record for the fastest rise from League Two to Premier League (6 seasons)', 'name_ptbr' => 'Recorde de ascensão mais rápida da League Two para a Premier League (6 temporadas)'],
            ['id_team' => 3, 'name' => 'Largest competitive victory (10-0 vs. Aldershot, 1990)', 'name_ptbr' => 'Maior vitória competitiva (10-0 vs. Aldershot, 1990)'],
            ['id_team' => 3, 'name' => 'First time reaching the FA Cup Quarter-finals (2020-21 & 2024-25 seasons)', 'name_ptbr' => 'Primeira vez a chegar às quartas de final da FA Cup (temporadas 2020-21 e 2024-25)'],
            ['id_team' => 3, 'name' => 'Highest transfer fee received (Dominic Solanke to Tottenham, £65m in 2025)', 'name_ptbr' => 'Maior taxa de transferência recebida (Dominic Solanke para o Tottenham, £65 milhões em 2025)'],
            ['id_team' => 3, 'name' => 'Most expensive departure (Dean Huijsen to Real Madrid, £50m in 2025)', 'name_ptbr' => 'Saída mais cara (Dean Huijsen para o Real Madrid, £50 milhões em 2025)'],
            ['id_team' => 4, 'name' => 'Highest ever top-flight league finish (5th in First Division, 1935-36)', 'name_ptbr' => 'Melhor colocação na primeira divisão (5º na Primeira Divisão, 1935-36)'],
            ['id_team' => 4, 'name' => 'Most competitive goals scored by a player (Jim Towers, 163 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Jim Towers, 163 gols)'],
            ['id_team' => 4, 'name' => 'Longest unbeaten run in the Premier League (12 games, 2022-23)', 'name_ptbr' => 'Maior sequência invicta na Premier League (12 jogos, 2022-23)'],
            ['id_team' => 4, 'name' => 'Highest points tally in the Premier League (59 points, 2022-23)', 'name_ptbr' => 'Maior pontuação na Premier League (59 pontos, 2022-23)'],
            ['id_team' => 4, 'name' => 'First promotion to the Premier League (2021)', 'name_ptbr' => 'Primeira promoção para a Premier League (2021)'],
            ['id_team' => 4, 'name' => 'Highest attendance at Griffin Park (38,678 vs Leicester City, 1949)', 'name_ptbr' => 'Maior público em Griffin Park (38.678 vs Leicester City, 1949)'],
            ['id_team' => 5, 'name' => 'Highest ever league finish (6th in Premier League, 2022-23)', 'name_ptbr' => 'Melhor colocação na liga (6º na Premier League, 2022-23)'],
            ['id_team' => 5, 'name' => 'Most competitive goals scored by a player (Tommy Cook, 123 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Tommy Cook, 123 gols)'],
            ['id_team' => 5, 'name' => 'First time qualifying for European competition (UEFA Europa League, 2023-24)', 'name_ptbr' => 'Primeira vez a se classificar para uma competição europeia (UEFA Europa League, 2023-24)'],
            ['id_team' => 5, 'name' => 'Record points tally in the Premier League (62 points, 2022-23)', 'name_ptbr' => 'Recorde de pontos na Premier League (62 pontos, 2022-23)'],
            ['id_team' => 5, 'name' => 'Longest unbeaten away run in the Premier League (9 games, 2022-23)', 'name_ptbr' => 'Maior sequência invicta fora de casa na Premier League (9 jogos, 2022-23)'],
            ['id_team' => 5, 'name' => 'Highest transfer fee received (Moisés Caicedo to Chelsea, £115m)', 'name_ptbr' => 'Maior taxa de transferência recebida (Moisés Caicedo para o Chelsea, £115 milhões)'],
            ['id_team' => 6, 'name' => 'Most UEFA Champions League titles by a London club (2 titles)', 'name_ptbr' => 'Mais títulos da UEFA Champions League por um clube de Londres (2 títulos)'],
            ['id_team' => 6, 'name' => 'Only London club to have won every major UEFA club competition', 'name_ptbr' => 'Único clube de Londres a ter vencido todas as principais competições de clubes da UEFA'],
            ['id_team' => 6, 'name' => 'Record for the most Premier League clean sheets in a season (25 in 2004-05)', 'name_ptbr' => 'Recorde de mais jogos sem sofrer gols em uma temporada da Premier League (25 em 2004-05)'],
            ['id_team' => 6, 'name' => 'Most competitive goals scored by a player (Frank Lampard, 211 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Frank Lampard, 211 gols)'],
            ['id_team' => 6, 'name' => 'Most points in a Premier League season (95 points in 2004-05)', 'name_ptbr' => 'Mais pontos em uma temporada da Premier League (95 pontos em 2004-05)'],
            ['id_team' => 6, 'name' => 'Longest unbeaten home run in Premier League (86 games, 2004-2008)', 'name_ptbr' => 'Maior sequência invicta em casa na Premier League (86 jogos, 2004-2008)'],
            ['id_team' => 6, 'name' => 'First English club to win the Premier League, FA Cup and League Cup in consecutive seasons.', 'name_ptbr' => 'Primeiro clube inglês a vencer a Premier League, FA Cup e Copa da Liga em temporadas consecutivas.'],
            ['id_team' => 7, 'name' => 'First major trophy won (FA Cup, 2024-25)', 'name_ptbr' => 'Primeiro grande troféu conquistado (FA Cup, 2024-25)'],
            ['id_team' => 7, 'name' => 'Highest ever Premier League points total (53 points, 2024-25)', 'name_ptbr' => 'Maior pontuação da história na Premier League (53 pontos, 2024-25)'],
            ['id_team' => 7, 'name' => 'Most competitive goals scored by a player (Peter Simpson, 165 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Peter Simpson, 165 gols)'],
            ['id_team' => 7, 'name' => 'Record for longest FA Cup run as a non-league team (Reached 4th Round as Athenian League side, 1906)', 'name_ptbr' => 'Recorde de maior campanha na FA Cup como time não-profissional (Chegou à 4ª rodada como time da Athenian League, 1906)'],
            ['id_team' => 7, 'name' => 'First qualification for UEFA Europa League (2025-26)', 'name_ptbr' => 'Primeira classificação para a UEFA Europa League (2025-26)'],
            ['id_team' => 7, 'name' => 'Most goals in a single Premier League season by a player (Jean-Philippe Mateta, 17 goals in 2024-25)', 'name_ptbr' => 'Mais gols em uma única temporada da Premier League por um jogador (Jean-Philippe Mateta, 17 gols em 2024-25)'],
            ['id_team' => 7, 'name' => 'Highest transfer fee received (Michael Olise to Bayern Munich, £50.8m)', 'name_ptbr' => 'Maior taxa de transferência recebida (Michael Olise para o Bayern de Munique, £50.8 milhões)'],
            ['id_team' => 8, 'name' => 'Most seasons in the English top flight (121 seasons, as of 2024-25)', 'name_ptbr' => 'Mais temporadas na primeira divisão inglesa (121 temporadas, a partir de 2024-25)'],
            ['id_team' => 8, 'name' => 'Most competitive goals scored by a player (Dixie Dean, 383 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Dixie Dean, 383 gols)'],
            ['id_team' => 8, 'name' => 'Highest number of League titles won (9 titles)', 'name_ptbr' => 'Maior número de títulos da Liga vencidos (9 títulos)'],
            ['id_team' => 8, 'name' => 'First English club to play 100 seasons in the top flight', 'name_ptbr' => 'Primeiro clube inglês a jogar 100 temporadas na primeira divisão'],
            ['id_team' => 8, 'name' => 'Highest attendance for a league match at Goodison Park (78,299 vs Liverpool, 1948)', 'name_ptbr' => 'Maior público em uma partida da liga em Goodison Park (78.299 vs Liverpool, 1948)'],
            ['id_team' => 8, 'name' => 'Longest unbroken period in the top flight (from 1954 to present)', 'name_ptbr' => 'Período mais longo ininterrupto na primeira divisão (de 1954 até o presente)'],
            ['id_team' => 8, 'name' => 'Player of the Year at 35 (Idrissa Gueye, 2024-25 season)', 'name_ptbr' => 'Jogador do Ano aos 35 anos (Idrissa Gueye, temporada 2024-25)'],
            ['id_team' => 9, 'name' => 'Highest ever Premier League points total (54 points, 2024-25)', 'name_ptbr' => 'Maior pontuação da história na Premier League (54 pontos, 2024-25)'],
            ['id_team' => 9, 'name' => 'Most competitive goals scored by a player (Gordon Davies, 178 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Gordon Davies, 178 gols)'],
            ['id_team' => 9, 'name' => 'Longest-serving London professional club (founded 1879)', 'name_ptbr' => 'Clube profissional de Londres com mais tempo de serviço (fundado em 1879)'],
            ['id_team' => 9, 'name' => 'Record for most league draws in a season (18 draws in 2002-03)', 'name_ptbr' => 'Recorde de mais empates na liga em uma temporada (18 empates em 2002-03)'],
            ['id_team' => 9, 'name' => 'Only English club to have reached the UEFA Europa League final while being relegated to the Championship in the same decade.', 'name_ptbr' => 'Único clube inglês a ter chegado à final da UEFA Europa League enquanto era rebaixado para a Championship na mesma década.'],
            ['id_team' => 9, 'name' => 'Record for most points dropped from winning positions in Premier League (28 points, 2024-25)', 'name_ptbr' => 'Recorde de mais pontos perdidos de posições de vitória na Premier League (28 pontos, 2024-25)'],
            ['id_team' => 10, 'name' => 'Only club to win the FA Cup and UEFA Cup, and finish in the top two divisions without ever winning the top division until 1962.', 'name_ptbr' => 'Único clube a vencer a FA Cup e a Copa da UEFA, e terminar nas duas primeiras divisões sem nunca ter vencido a primeira divisão até 1962.'],
            ['id_team' => 10, 'name' => 'Most competitive goals scored by a player (Ray Crawford, 171 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Ray Crawford, 171 gols)'],
            ['id_team' => 10, 'name' => 'Record for most promotions to the Premier League from the Championship (3 times, most recently 2024)', 'name_ptbr' => 'Recorde de mais promoções para a Premier League a partir da Championship (3 vezes, mais recentemente em 2024)'],
            ['id_team' => 10, 'name' => 'Only club to win the First Division title in their first season after promotion (1961-62)', 'name_ptbr' => 'Único clube a vencer o título da Primeira Divisão em sua primeira temporada após a promoção (1961-62)'],
            ['id_team' => 10, 'name' => 'Only British club never to have been relegated below the third tier of English football.', 'name_ptbr' => 'Único clube britânico a nunca ter sido rebaixado abaixo da terceira divisão do futebol inglês.'],
            ['id_team' => 11, 'name' => 'Highest odds Premier League title winner (5000/1 in 2015-16)', 'name_ptbr' => 'Vencedor do título da Premier League com as maiores odds (5000/1 em 2015-16)'],
            ['id_team' => 11, 'name' => 'Most competitive goals scored by a player (Arthur Chandler, 273 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Arthur Chandler, 273 gols)'],
            ['id_team' => 11, 'name' => 'First club to win the Premier League under a non-British manager (Claudio Ranieri)', 'name_ptbr' => 'Primeiro clube a vencer a Premier League sob um treinador não-britânico (Claudio Ranieri)'],
            ['id_team' => 11, 'name' => 'Record for the longest consecutive home games without scoring (6 games, 2024-25)', 'name_ptbr' => 'Recorde de mais jogos consecutivos em casa sem marcar (6 jogos, 2024-25)'],
            ['id_team' => 11, 'name' => 'Highest transfer fee received (Harry Maguire to Manchester United, £80m)', 'name_ptbr' => 'Maior taxa de transferência recebida (Harry Maguire para o Manchester United, £80 milhões)'],
            ['id_team' => 11, 'name' => 'First club to win the FA Cup for the first time after 4 previous final defeats (2021)', 'name_ptbr' => 'Primeiro clube a vencer a FA Cup pela primeira vez após 4 derrotas em finais anteriores (2021)'],
            ['id_team' => 12, 'name' => 'Most League Cups won (10 titles)', 'name_ptbr' => 'Mais Copas da Liga vencidas (10 títulos)'],
            ['id_team' => 12, 'name' => 'Most European Cup/Champions League titles won by an English club (6 titles)', 'name_ptbr' => 'Mais títulos da Copa Europeia/Champions League vencidos por um clube inglês (6 títulos)'],
            ['id_team' => 12, 'name' => 'Most competitive goals scored by a player (Ian Rush, 346 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Ian Rush, 346 gols)'],
            ['id_team' => 12, 'name' => 'Record for most points in a Premier League season without winning the title (97 points in 2018-19)', 'name_ptbr' => 'Recorde de mais pontos em uma temporada da Premier League sem vencer o título (97 pontos em 2018-19)'],
            ['id_team' => 12, 'name' => 'Longest unbeaten home league run (68 games, 2017-2021)', 'name_ptbr' => 'Maior sequência invicta em casa na liga (68 jogos, 2017-2021)'],
            ['id_team' => 12, 'name' => 'First English club to win the treble of League, League Cup and European Cup in a single season (1983-84)', 'name_ptbr' => 'Primeiro clube inglês a conquistar a tríplice coroa da Liga, Copa da Liga e Copa Europeia em uma única temporada (1983-84)'],
            ['id_team' => 12, 'name' => 'Most consecutive penalty shootout wins (5, from 2022 to 2024)', 'name_ptbr' => 'Mais vitórias consecutivas em disputas de pênaltis (5, de 2022 a 2024)'],
            ['id_team' => 13, 'name' => 'Only club to go from non-league to Premier League (2014-2023)', 'name_ptbr' => 'Único clube a ir da liga não-profissional para a Premier League (2014-2023)'],
            ['id_team' => 13, 'name' => 'Most competitive goals scored by a player (Joe Payne, 143 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Joe Payne, 143 gols)'],
            ['id_team' => 13, 'name' => 'First club to win the League Cup on an artificial pitch (1988)', 'name_ptbr' => 'Primeiro clube a vencer a Copa da Liga em um campo artificial (1988)'],
            ['id_team' => 13, 'name' => 'Record for back-to-back relegations from Premier League to League One (2024-2025)', 'name_ptbr' => 'Recorde de rebaixamentos consecutivos da Premier League para a League One (2024-2025)'],
            ['id_team' => 13, 'name' => 'First club to be in the top flight, then non-league, and then back to the top flight.', 'name_ptbr' => 'Primeiro clube a estar na primeira divisão, depois na liga não-profissional e depois de volta à primeira divisão.'],
            ['id_team' => 14, 'name' => 'Most Premier League titles won in a row (4 titles, 2020-2024)', 'name_ptbr' => 'Mais títulos da Premier League vencidos consecutivamente (4 títulos, 2020-2024)'],
            ['id_team' => 14, 'name' => 'Most competitive goals scored by a player (Sergio Agüero, 260 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Sergio Agüero, 260 gols)'],
            ['id_team' => 14, 'name' => 'Record for most points in a Premier League season (100 points in 2017-18)', 'name_ptbr' => 'Recorde de mais pontos em uma temporada da Premier League (100 pontos em 2017-18)'],
            ['id_team' => 14, 'name' => 'Most goals scored in a Premier League season (106 goals in 2017-18)', 'name_ptbr' => 'Mais gols marcados em uma temporada da Premier League (106 gols em 2017-18)'],
            ['id_team' => 14, 'name' => 'First English club to achieve the domestic treble (2018-19)', 'name_ptbr' => 'Primeiro clube inglês a conquistar a tríplice coroa nacional (2018-19)'],
            ['id_team' => 14, 'name' => 'Fastest goal in a Champions League final (Ilkay Gündogan, 12 seconds in 2023)', 'name_ptbr' => 'Gol mais rápido em uma final da Champions League (Ilkay Gündogan, 12 segundos em 2023)'],
            ['id_team' => 14, 'name' => 'Most consecutive away league wins (12 games, 2020-21)', 'name_ptbr' => 'Mais vitórias consecutivas fora de casa na liga (12 jogos, 2020-21)'],
            ['id_team' => 15, 'name' => 'Most English top-flight League titles (20 titles)', 'name_ptbr' => 'Mais títulos da Liga inglesa (20 títulos)'],
            ['id_team' => 15, 'name' => 'Most FA Community Shields won (21 titles)', 'name_ptbr' => 'Mais FA Community Shields vencidas (21 títulos)'],
            ['id_team' => 15, 'name' => 'Most competitive goals scored by a player (Wayne Rooney, 253 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Wayne Rooney, 253 gols)'],
            ['id_team' => 15, 'name' => 'First English club to win the European Cup (1968)', 'name_ptbr' => 'Primeiro clube inglês a vencer a Copa dos Campeões (1968)'],
            ['id_team' => 15, 'name' => 'Record for highest average attendance in Premier League history', 'name_ptbr' => 'Recorde de maior média de público na história da Premier League'],
            ['id_team' => 15, 'name' => 'Only English club to win the Treble (Premier League, FA Cup, Champions League in 1998-99)', 'name_ptbr' => 'Único clube inglês a vencer a Tríplice Coroa (Premier League, FA Cup, Champions League em 1998-99)'],
            ['id_team' => 15, 'name' => 'Most FA Cup wins (13 titles)', 'name_ptbr' => 'Mais FA Cups vencidas (13 títulos)'],
            ['id_team' => 15, 'name' => 'Lowest Premier League points total (59 points in 2024-25)', 'name_ptbr' => 'Menor pontuação na Premier League (59 pontos em 2024-25)'],
            ['id_team' => 15, 'name' => 'Most league losses in a Premier League season (15 losses in 2024-25)', 'name_ptbr' => 'Mais derrotas na liga em uma temporada da Premier League (15 derrotas em 2024-25)'],
            ['id_team' => 16, 'name' => 'Most competitive goals scored by a player (Alan Shearer, 206 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Alan Shearer, 206 gols)'],
            ['id_team' => 16, 'name' => 'Highest Premier League finish (2nd, 1995-96 and 1996-97)', 'name_ptbr' => 'Melhor colocação na Premier League (2º, 1995-96 e 1996-97)'],
            ['id_team' => 16, 'name' => 'Longest unbeaten run in the Premier League (14 games, 2022-23)', 'name_ptbr' => 'Maior sequência invicta na Premier League (14 jogos, 2022-23)'],
            ['id_team' => 16, 'name' => 'Record for most consecutive Premier League victories (9 wins, 2001-02)', 'name_ptbr' => 'Recorde de mais vitórias consecutivas na Premier League (9 vitórias, 2001-02)'],
            ['id_team' => 16, 'name' => 'Largest home attendance (68,386 vs Chelsea, 1930)', 'name_ptbr' => 'Maior público em casa (68.386 vs Chelsea, 1930)'],
            ['id_team' => 17, 'name' => 'Only club to win the European Cup more times than their domestic league title (2 European Cups, 1 League title)', 'name_ptbr' => 'Único clube a vencer a Copa dos Campeões mais vezes do que o título da liga nacional (2 Copas dos Campeões, 1 título da Liga)'],
            ['id_team' => 17, 'name' => 'Most competitive goals scored by a player (Arthur Capes, 104 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Arthur Capes, 104 gols)'],
            ['id_team' => 17, 'name' => 'Record for the longest unbeaten league run in English football (42 games, 1978)', 'name_ptbr' => 'Recorde de maior sequência invicta na liga inglesa (42 jogos, 1978)'],
            ['id_team' => 17, 'name' => 'First club to win the European Cup after being promoted to the top division (1979)', 'name_ptbr' => 'Primeiro clube a vencer a Copa dos Campeões após ser promovido à primeira divisão (1979)'],
            ['id_team' => 17, 'name' => 'Most consecutive League Cup wins (2, 1978 and 1979)', 'name_ptbr' => 'Mais vitórias consecutivas na Copa da Liga (2, 1978 e 1979)'],
            ['id_team' => 18, 'name' => 'Most competitive goals scored by a player (Mick Channon, 185 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Mick Channon, 185 gols)'],
            ['id_team' => 18, 'name' => 'Only club to have won the FA Cup while outside the top flight (1976)', 'name_ptbr' => 'Único clube a ter vencido a FA Cup enquanto estava fora da primeira divisão (1976)'],
            ['id_team' => 18, 'name' => 'Record for most players produced by its academy to play for the England senior team', 'name_ptbr' => 'Recorde de mais jogadores produzidos por sua academia a jogar pela seleção principal da Inglaterra'],
            ['id_team' => 18, 'name' => 'Highest Premier League finish (6th, 2015-16)', 'name_ptbr' => 'Melhor colocação na Premier League (6º, 2015-16)'],
            ['id_team' => 18, 'name' => 'Record for the largest margin of victory in a Premier League game (9-0 vs Leicester City, 2019, and vs Manchester United, 2021)', 'name_ptbr' => 'Recorde de maior margem de vitória em um jogo da Premier League (9-0 vs Leicester City, 2019, e vs Manchester United, 2021)'],
            ['id_team' => 19, 'name' => 'First British club to win a European trophy (European Cup Winners\' Cup, 1963)', 'name_ptbr' => 'Primeiro clube britânico a vencer um troféu europeu (Recopa Europeia, 1963)'],
            ['id_team' => 19, 'name' => 'First club in the 20th century to achieve the League and FA Cup Double (1960-61)', 'name_ptbr' => 'Primeiro clube no século XX a conquistar a Dobradinha da Liga e da FA Cup (1960-61)'],
            ['id_team' => 19, 'name' => 'Most competitive goals scored by a player (Harry Kane, 280 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Harry Kane, 280 gols)'],
            ['id_team' => 19, 'name' => 'Most League Cups won by any club (4 titles, joint record)', 'name_ptbr' => 'Mais Copas da Liga vencidas por qualquer clube (4 títulos, recorde conjunto)'],
            ['id_team' => 19, 'name' => 'Highest attendance at their new stadium (62,850 vs Arsenal, 2023)', 'name_ptbr' => 'Maior público em seu novo estádio (62.850 vs Arsenal, 2023)'],
            ['id_team' => 19, 'name' => 'Most consecutive seasons scoring in the Premier League (all 33 seasons, ongoing)', 'name_ptbr' => 'Mais temporadas consecutivas marcando gols na Premier League (todas as 33 temporadas, em andamento)'],
            ['id_team' => 20, 'name' => 'Most competitive goals scored by a player (Vic Watson, 326 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Vic Watson, 326 gols)'],
            ['id_team' => 20, 'name' => 'Only English club to win the UEFA Europa Conference League (2023)', 'name_ptbr' => 'Único clube inglês a vencer a UEFA Europa Conference League (2023)'],
            ['id_team' => 20, 'name' => 'Record for most FA Cup wins without winning the league (3 titles)', 'name_ptbr' => 'Recorde de mais vitórias na FA Cup sem vencer a liga (3 títulos)'],
            ['id_team' => 20, 'name' => 'Highest Premier League finish (5th, 1998-99 and 2020-21)', 'name_ptbr' => 'Melhor colocação na Premier League (5º, 1998-99 e 2020-21)'],
            ['id_team' => 20, 'name' => 'Most consecutive games without a draw in the Premier League (19 games, 2003-04)', 'name_ptbr' => 'Mais jogos consecutivos sem empate na Premier League (19 jogos, 2003-04)'],
            ['id_team' => 21, 'name' => 'Most competitive goals scored by a player (Steve Bull, 306 goals)', 'name_ptbr' => 'Mais gols competitivos marcados por um jogador (Steve Bull, 306 gols)'],
            ['id_team' => 21, 'name' => 'First club to play in the European Cup (1954-55)', 'name_ptbr' => 'Primeiro clube a jogar na Copa dos Campeões (1954-55)'],
            ['id_team' => 21, 'name' => 'Most League titles won by a non-London club (3 titles, joint record)', 'name_ptbr' => 'Mais títulos da Liga vencidos por um clube não-londrino (3 títulos, recorde conjunto)'],
            ['id_team' => 21, 'name' => 'Longest unbeaten home run in the Premier League (11 games, 2019)', 'name_ptbr' => 'Maior sequência invicta em casa na Premier League (11 jogos, 2019)'],
            ['id_team' => 21, 'name' => 'Record for the highest number of points in the Championship (103 points, 2017-18)', 'name_ptbr' => 'Recorde de maior número de pontos na Championship (103 pontos, 2017-18)']
        ]);
    }
}
