<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class teams extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('teams')->insert([
                // Premier League (id_league = 1)
                ['name'=>'Arsenal','city'=>'London','country'=>'England','id_league'=>1,'size'=>5,'stadium'=>'Emirates Stadium'],
                ['name'=>'Aston Villa','city'=>'Birmingham','country'=>'England','id_league'=>1,'size'=>4,'stadium'=>'Villa Park'],
                ['name'=>'Bournemouth','city'=>'Bournemouth','country'=>'England','id_league'=>1,'size'=>1,'stadium'=>'Dean Court (Vitality Stadium)'],
                ['name'=>'Brentford','city'=>'London','country'=>'England','id_league'=>1,'size'=>1,'stadium'=>'Brentford Community Stadium'],
                ['name'=>'Brighton & Hove Albion','city'=>'Falmer','country'=>'England','id_league'=>1,'size'=>2,'stadium'=>'American Express Stadium'],
                ['name'=>'Chelsea','city'=>'London','country'=>'England','id_league'=>1,'size'=>5,'stadium'=>'Stamford Bridge'],
                ['name'=>'Crystal Palace','city'=>'London','country'=>'England','id_league'=>1,'size'=>2,'stadium'=>'Selhurst Park'],
                ['name'=>'Everton','city'=>'Liverpool','country'=>'England','id_league'=>1,'size'=>4,'stadium'=>'Everton Stadium'],
                ['name'=>'Fulham','city'=>'London','country'=>'England','id_league'=>1,'size'=>2,'stadium'=>'Craven Cottage'],
                ['name'=>'Ipswich Town','city'=>'Ipswich','country'=>'England','id_league'=>1,'size'=>3,'stadium'=>'Portman Road'],
                ['name'=>'Leicester City','city'=>'Leicester','country'=>'England','id_league'=>1,'size'=>4,'stadium'=>'King Power Stadium'],
                ['name'=>'Liverpool','city'=>'Liverpool','country'=>'England','id_league'=>1,'size'=>5,'stadium'=>'Anfield'],
                ['name'=>'Luton Town','city'=>'Luton','country'=>'England','id_league'=>1,'size'=>1,'stadium'=>'Kenilworth Road'],
                ['name'=>'Manchester City','city'=>'Manchester','country'=>'England','id_league'=>1,'size'=>5,'stadium'=>'Etihad Stadium'],
                ['name'=>'Manchester United','city'=>'Manchester','country'=>'England','id_league'=>1,'size'=>5,'stadium'=>'Old Trafford'],
                ['name'=>'Newcastle United','city'=>'Newcastle upon Tyne','country'=>'England','id_league'=>1,'size'=>4,'stadium'=>'St James\' Park'],
                ['name'=>'Nottingham Forest','city'=>'West Bridgford','country'=>'England','id_league'=>1,'size'=>4,'stadium'=>'The City Ground'],
                ['name'=>'Southampton','city'=>'Southampton','country'=>'England','id_league'=>1,'size'=>2,'stadium'=>'St Mary’s Stadium'],
                ['name'=>'Tottenham Hotspur','city'=>'London','country'=>'England','id_league'=>1,'size'=>4,'stadium'=>'Tottenham Hotspur Stadium'],
                ['name'=>'West Ham United','city'=>'London','country'=>'England','id_league'=>1,'size'=>4,'stadium'=>'London Stadium'],
                ['name'=>'Wolverhampton Wanderers','city'=>'Wolverhampton','country'=>'England','id_league'=>1,'size'=>3,'stadium'=>'Molineux Stadium'],

                // Championship (id_league = 2)
                ['name'=>'Blackburn Rovers','city'=>'Blackburn','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Ewood Park'],
                ['name'=>'Birmingham City','city'=>'Birmingham','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'St Andrew’s'],
                ['name'=>'Bristol City','city'=>'Bristol','country'=>'England','id_league'=>2,'size'=>2,'stadium'=>'Ashton Gate'],
                ['name'=>'Burnley','city'=>'Burnley','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Turf Moor'],
                ['name'=>'Cardiff City','city'=>'Cardiff','country'=>'Wales','id_league'=>2,'size'=>2,'stadium'=>'Cardiff City Stadium'],
                ['name'=>'Coventry City','city'=>'Coventry','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Coventry Building Society Arena'],
                ['name'=>'Derby County','city'=>'Derby','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Pride Park Stadium'],
                ['name'=>'Hull City','city'=>'Kingston upon Hull','country'=>'England','id_league'=>2,'size'=>2,'stadium'=>'MKM Stadium'],
                ['name'=>'Leeds United','city'=>'Leeds','country'=>'England','id_league'=>2,'size'=>4,'stadium'=>'Elland Road'],
                ['name'=>'Luton Town','city'=>'Luton','country'=>'England','id_league'=>2,'size'=>2,'stadium'=>'Kenilworth Road'],
                ['name'=>'Middlesbrough','city'=>'Middlesbrough','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Riverside Stadium'],
                ['name'=>'Millwall','city'=>'London','country'=>'England','id_league'=>2,'size'=>2,'stadium'=>'The Den'],
                ['name'=>'Norwich City','city'=>'Norwich','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Carrow Road'],
                ['name'=>'Oxford United','city'=>'Oxford','country'=>'England','id_league'=>2,'size'=>1,'stadium'=>'Santiago Stadium'],
                ['name'=>'Plymouth Argyle','city'=>'Plymouth','country'=>'England','id_league'=>2,'size'=>2,'stadium'=>'Home Park'],
                ['name'=>'Portsmouth','city'=>'Portsmouth','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Fratton Park'],
                ['name'=>'Preston North End','city'=>'Preston','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Deepdale'],
                ['name'=>'Queens Park Rangers','city'=>'London','country'=>'England','id_league'=>2,'size'=>2,'stadium'=>'Loftus Road'],
                ['name'=>'Sheffield United','city'=>'Sheffield','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Bramall Lane'],
                ['name'=>'Sheffield Wednesday','city'=>'Sheffield','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'Hillsborough Stadium'],
                ['name'=>'Stoke City','city'=>'Stoke-on-Trent','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'bet365 Stadium'],
                ['name'=>'Sunderland','city'=>'Sunderland','country'=>'England','id_league'=>2,'size'=>4,'stadium'=>'Stadium of Light'],
                ['name'=>'Swansea City','city'=>'Swansea','country'=>'Wales','id_league'=>2,'size'=>2,'stadium'=>'Liberty Stadium'],
                ['name'=>'Watford','city'=>'Watford','country'=>'England','id_league'=>2,'size'=>2,'stadium'=>'Vicarage Road'],
                ['name'=>'West Bromwich Albion','city'=>'West Bromwich','country'=>'England','id_league'=>2,'size'=>3,'stadium'=>'The Hawthorns'],

                // League One (id_league = 3)
                ['name'=>'Barnsley','city'=>'Barnsley','country'=>'England','id_league'=>3,'size'=>3,'stadium'=>'Oakwell'],
                ['name'=>'Birmingham City','city'=>'Birmingham','country'=>'England','id_league'=>3,'size'=>4,'stadium'=>'St Andrew’s'],
                ['name'=>'Blackpool','city'=>'Blackpool','country'=>'England','id_league'=>3,'size'=>3,'stadium'=>'Bloomfield Road'],
                ['name'=>'Bolton Wanderers','city'=>'Horwich','country'=>'England','id_league'=>3,'size'=>4,'stadium'=>'University of Bolton Stadium'],
                ['name'=>'Bristol Rovers','city'=>'Bristol','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Memorial Stadium'],
                ['name'=>'Burton Albion','city'=>'Burton upon Trent','country'=>'England','id_league'=>3,'size'=>1,'stadium'=>'Pirelli Stadium'],
                ['name'=>'Cambridge United','city'=>'Cambridge','country'=>'England','id_league'=>3,'size'=>1,'stadium'=>'Abbey Stadium'],
                ['name'=>'Charlton Athletic','city'=>'London','country'=>'England','id_league'=>3,'size'=>3,'stadium'=>'The Valley'],
                ['name'=>'Crawley Town','city'=>'Crawley','country'=>'England','id_league'=>3,'size'=>1,'stadium'=>'Broadfield Stadium'],
                ['name'=>'Exeter City','city'=>'Exeter','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'St James Park'],
                ['name'=>'Huddersfield Town','city'=>'Huddersfield','country'=>'England','id_league'=>3,'size'=>3,'stadium'=>'John Smith’s Stadium'],
                ['name'=>'Leyton Orient','city'=>'London','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Brisbane Road'],
                ['name'=>'Lincoln City','city'=>'Lincoln','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Sincil Bank'],
                ['name'=>'Mansfield Town','city'=>'Mansfield','country'=>'England','id_league'=>3,'size'=>1,'stadium'=>'One Call Stadium'],
                ['name'=>'Northampton Town','city'=>'Northampton','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Sixfields Stadium'],
                ['name'=>'Peterborough United','city'=>'Peterborough','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'London Road Stadium'],
                ['name'=>'Plymouth Argyle','city'=>'Plymouth','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Home Park'],
                ['name'=>'Port Vale','city'=>'Stoke-on-Trent','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Vale Park'],
                ['name'=>'Reading','city'=>'Reading','country'=>'England','id_league'=>3,'size'=>3,'stadium'=>'Select Car Leasing Stadium'],
                ['name'=>'Rotherham United','city'=>'Rotherham','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'New York Stadium'],
                ['name'=>'Shrewsbury Town','city'=>'Shrewsbury','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Montgomery Waters Meadow'],
                ['name'=>'Stevenage','city'=>'Stevenage','country'=>'England','id_league'=>3,'size'=>1,'stadium'=>'The Lamex Stadium'],
                ['name'=>'Stockport County','city'=>'Stockport','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Edgeley Park'],
                ['name'=>'Wigan Athletic','city'=>'Wigan','country'=>'England','id_league'=>3,'size'=>3,'stadium'=>'DW Stadium'],
                ['name'=>'Wrexham','city'=>'Wrexham','country'=>'Wales','id_league'=>3,'size'=>3,'stadium'=>'Racecourse Ground'],
                ['name'=>'Wycombe Wanderers','city'=>'High Wycombe','country'=>'England','id_league'=>3,'size'=>2,'stadium'=>'Adams Park'],

                // EFL League Two (4)
                ['name' => 'Accrington Stanley', 'city' => 'Accrington', 'country' => 'England', 'id_league' => 4, 'size' => 1, 'stadium' => 'Crown Ground'],
                ['name' => 'AFC Wimbledon', 'city' => 'London', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Plough Lane'],
                ['name' => 'Barrow', 'city' => 'Barrow-in-Furness', 'country' => 'England', 'id_league' => 4, 'size' => 1, 'stadium' => 'Holker Street'],
                ['name' => 'Bradford City', 'city' => 'Bradford', 'country' => 'England', 'id_league' => 4, 'size' => 3, 'stadium' => 'Valley Parade'],
                ['name' => 'Bromley', 'city' => 'London', 'country' => 'England', 'id_league' => 4, 'size' => 1, 'stadium' => 'Hayes Lane'],
                ['name' => 'Carlisle United', 'city' => 'Carlisle', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Brunton Park'],
                ['name' => 'Cheltenham Town', 'city' => 'Cheltenham', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Whaddon Road'],
                ['name' => 'Chesterfield', 'city' => 'Chesterfield', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'SMH Group Stadium'],
                ['name' => 'Colchester United', 'city' => 'Colchester', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Colchester Community Stadium'],
                ['name' => 'Crewe Alexandra', 'city' => 'Crewe', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Mornflake Stadium'],
                ['name' => 'Doncaster Rovers', 'city' => 'Doncaster', 'country' => 'England', 'id_league' => 4, 'size' => 3, 'stadium' => 'Eco-Power Stadium'],
                ['name' => 'Fleetwood Town', 'city' => 'Fleetwood', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Highbury Stadium'],
                ['name' => 'Gillingham', 'city' => 'Gillingham', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Priestfield Stadium'],
                ['name' => 'Grimsby Town', 'city' => 'Cleethorpes', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Blundell Park'],
                ['name' => 'Harrogate Town', 'city' => 'Harrogate', 'country' => 'England', 'id_league' => 4, 'size' => 1, 'stadium' => 'EnviroVent Stadium'],
                ['name' => 'Milton Keynes Dons', 'city' => 'Milton Keynes', 'country' => 'England', 'id_league' => 4, 'size' => 3, 'stadium' => 'Stadium MK'],
                ['name' => 'Morecambe', 'city' => 'Morecambe', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Mazuma Mobile Stadium'],
                ['name' => 'Newport County', 'city' => 'Newport', 'country' => 'Wales', 'id_league' => 4, 'size' => 2, 'stadium' => 'Rodney Parade'],
                ['name' => 'Notts County', 'city' => 'Nottingham', 'country' => 'England', 'id_league' => 4, 'size' => 3, 'stadium' => 'Meadow Lane'],
                ['name' => 'Port Vale', 'city' => 'Stoke-on-Trent', 'country' => 'England', 'id_league' => 4, 'size' => 3, 'stadium' => 'Vale Park'],
                ['name' => 'Salford City', 'city' => 'Salford', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Moor Lane'],
                ['name' => 'Swindon Town', 'city' => 'Swindon', 'country' => 'England', 'id_league' => 4, 'size' => 3, 'stadium' => 'County Ground'],
                ['name' => 'Tranmere Rovers', 'city' => 'Birkenhead', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Prenton Park'],
                ['name' => 'Walsall', 'city' => 'Walsall', 'country' => 'England', 'id_league' => 4, 'size' => 2, 'stadium' => 'Bescot Stadium'],

                // LaLiga EA SPORTS (5)
                ['name' => 'Alavés', 'city' => 'Vitoria-Gasteiz', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio de Mendizorroza', 'size' => 3],
                ['name' => 'Athletic Club', 'city' => 'Bilbao', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio de San Mamés', 'size' => 4],
                ['name' => 'Atlético Madrid', 'city' => 'Madrid', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Cívitas Metropolitano', 'size' => 5],
                ['name' => 'Barcelona', 'city' => 'Barcelona', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio Olímpico Lluís Companys', 'size' => 5],
                ['name' => 'Celta Vigo', 'city' => 'Vigo', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio ABANCA-Balaídos', 'size' => 2],
                ['name' => 'Espanyol', 'city' => 'Cornellà de Llobregat', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'RCDE Stadium', 'size' => 2],
                ['name' => 'Getafe', 'city' => 'Getafe', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Coliseum Alfonso Pérez', 'size' => 2],
                ['name' => 'Girona', 'city' => 'Girona', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadi Municipal de Montilivi', 'size' => 1],
                ['name' => 'Las Palmas', 'city' => 'Las Palmas de Gran Canaria', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio de Gran Canaria', 'size' => 2],
                ['name' => 'Leganés', 'city' => 'Leganés', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio Municipal de Butarque', 'size' => 1],
                ['name' => 'Mallorca', 'city' => 'Palma', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Visit Mallorca Estadi', 'size' => 2],
                ['name' => 'Osasuna', 'city' => 'Pamplona', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio El Sadar', 'size' => 2],
                ['name' => 'Rayo Vallecano', 'city' => 'Madrid', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio de Vallecas', 'size' => 2],
                ['name' => 'Real Betis', 'city' => 'Sevilla', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio Benito Villamarín', 'size' => 3],
                ['name' => 'Real Madrid', 'city' => 'Madrid', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio Santiago Bernabéu', 'size' => 5],
                ['name' => 'Real Sociedad', 'city' => 'San Sebastián', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Reale Arena', 'size' => 3],
                ['name' => 'Sevilla', 'city' => 'Sevilla', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio Ramón Sánchez Pizjuán', 'size' => 3],
                ['name' => 'Valencia', 'city' => 'Valencia', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio Mestalla', 'size' => 3],
                ['name' => 'Valladolid', 'city' => 'Valladolid', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio José Zorrilla', 'size' => 2],
                ['name' => 'Villarreal', 'city' => 'Villarreal', 'country' => 'Spain', 'id_league' => 5, 'stadium' => 'Estadio de la Cerámica', 'size' => 2],

                // LaLiga Hypermotion (6)
                ['name' => 'Almería', 'city' => 'Almería', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio de los Juegos Mediterráneos', 'size' => 2],
                ['name' => 'Albacete', 'city' => 'Albacete', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Carlos Belmonte', 'size' => 1],
                ['name' => 'Andorra', 'city' => 'Andorra la Vella', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadi Nacional', 'size' => 1],
                ['name' => 'Barcelona Atlètic', 'city' => 'Barcelona', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadi Johan Cruyff', 'size' => 2],
                ['name' => 'Burgos', 'city' => 'Burgos', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio El Plantío', 'size' => 1],
                ['name' => 'Castellón', 'city' => 'Castellón de la Plana', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Castalia', 'size' => 1],
                ['name' => 'Eldense', 'city' => 'Elda', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Nuevo Pepico Amat', 'size' => 1],
                ['name' => 'Girona', 'city' => 'Girona', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadi Montilivi', 'size' => 2],
                ['name' => 'Granada', 'city' => 'Granada', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Nuevo Los Cármenes', 'size' => 3],
                ['name' => 'Ibiza', 'city' => 'Ibiza', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Can Misses', 'size' => 1],
                ['name' => 'Las Palmas', 'city' => 'Las Palmas de Gran Canaria', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Gran Canaria', 'size' => 2],
                ['name' => 'Levante', 'city' => 'Valencia', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadi Ciutat de València', 'size' => 3],
                ['name' => 'Lugo', 'city' => 'Lugo', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Anxo Carro', 'size' => 1],
                ['name' => 'Málaga', 'city' => 'Málaga', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'La Rosaleda', 'size' => 3],
                ['name' => 'Mirandés', 'city' => 'Miranda de Ebro', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Municipal de Anduva', 'size' => 1],
                ['name' => 'Ponferradina', 'city' => 'Ponferrada', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio El Toralín', 'size' => 1],
                ['name' => 'Real Oviedo', 'city' => 'Oviedo', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Carlos Tartiere', 'size' => 2],
                ['name' => 'Real Sporting', 'city' => 'Gijón', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio El Molinón', 'size' => 2],
                ['name' => 'Real Zaragoza', 'city' => 'Zaragoza', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'La Romareda', 'size' => 3],
                ['name' => 'Rayo Vallecano', 'city' => 'Madrid', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio de Vallecas', 'size' => 2],
                ['name' => 'Tenerife', 'city' => 'Santa Cruz de Tenerife', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Estadio Heliodoro Rodríguez López', 'size' => 2],
                ['name' => 'Villarreal B', 'city' => 'Villarreal', 'country' => 'Spain', 'id_league' => 6, 'stadium' => 'Ciudad Deportiva Villarreal CF', 'size' => 1],

                // Bundesliga (7)
                ['name' => 'Bayern Munich', 'city' => 'Munich', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Allianz Arena', 'size' => 5],
                ['name' => 'Borussia Dortmund', 'city' => 'Dortmund', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Signal Iduna Park', 'size' => 5],
                ['name' => 'RB Leipzig', 'city' => 'Leipzig', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Red Bull Arena', 'size' => 4],
                ['name' => 'Bayer Leverkusen', 'city' => 'Leverkusen', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'BayArena', 'size' => 4],
                ['name' => 'Eintracht Frankfurt', 'city' => 'Frankfurt', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Deutsche Bank Park', 'size' => 4],
                ['name' => 'VfB Stuttgart', 'city' => 'Stuttgart', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'MHPArena', 'size' => 4],
                ['name' => 'Borussia Mönchengladbach', 'city' => 'Mönchengladbach', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Borussia-Park', 'size' => 3],
                ['name' => 'Werder Bremen', 'city' => 'Bremen', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Weserstadion', 'size' => 3],
                ['name' => 'FC Köln', 'city' => 'Cologne', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'RheinEnergieStadion', 'size' => 3],
                ['name' => 'VfL Wolfsburg', 'city' => 'Wolfsburg', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Volkswagen Arena', 'size' => 3],
                ['name' => 'SC Freiburg', 'city' => 'Freiburg im Breisgau', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Europa-Park Stadion', 'size' => 2],
                ['name' => 'FC Augsburg', 'city' => 'Augsburg', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'WWK Arena', 'size' => 2],
                ['name' => 'TSG Hoffenheim', 'city' => 'Sinsheim', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'PreZero Arena', 'size' => 2],
                ['name' => 'Mainz 05', 'city' => 'Mainz', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Mewa Arena', 'size' => 2],
                ['name' => 'Union Berlin', 'city' => 'Berlin', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Stadion An der Alten Försterei', 'size' => 2],
                ['name' => 'VfL Bochum', 'city' => 'Bochum', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Vonovia Ruhrstadion', 'size' => 1],
                ['name' => 'Eintracht Heidenheim', 'city' => 'Heidenheim', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Voith-Arena', 'size' => 1],
                ['name' => 'SC Paderborn', 'city' => 'Paderborn', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Benteler Arena', 'size' => 1],
                ['name' => 'FC St. Pauli', 'city' => 'Hamburg', 'country' => 'Germany', 'id_league' => 7, 'stadium' => 'Millerntor-Stadion', 'size' => 2],

                // 2. Bundesliga (8)
                ['name' => 'Hertha BSC', 'city' => 'Berlin', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Olympiastadion', 'size' => 4],
                ['name' => 'Hamburger SV', 'city' => 'Hamburg', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Volksparkstadion', 'size' => 5],
                ['name' => 'Schalke 04', 'city' => 'Gelsenkirchen', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Veltins-Arena', 'size' => 5],
                ['name' => '1. FC Köln', 'city' => 'Cologne', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'RheinEnergieStadion', 'size' => 4],
                ['name' => '1. FC Nürnberg', 'city' => 'Nuremberg', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Max-Morlock-Stadion', 'size' => 3],
                ['name' => 'Hannover 96', 'city' => 'Hanover', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Heinz von Heiden Arena', 'size' => 3],
                ['name' => '1. FC Kaiserslautern', 'city' => 'Kaiserslautern', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Fritz-Walter-Stadion', 'size' => 4],
                ['name' => 'Eintracht Braunschweig', 'city' => 'Braunschweig', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Eintracht-Stadion', 'size' => 2],
                ['name' => 'Darmstadt 98', 'city' => 'Darmstadt', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Merck-Stadion am Böllenfalltor', 'size' => 2],
                ['name' => 'Fortuna Düsseldorf', 'city' => 'Düsseldorf', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Merkur Spiel-Arena', 'size' => 4],
                ['name' => 'Karlsruher SC', 'city' => 'Karlsruhe', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'BBBank Wildpark', 'size' => 2],
                ['name' => '1. FC Magdeburg', 'city' => 'Magdeburg', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'MDCC-Arena', 'size' => 2],
                ['name' => 'SC Paderborn', 'city' => 'Paderborn', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Home Deluxe Arena', 'size' => 2],
                ['name' => 'SV Elversberg', 'city' => 'Spiesen-Elversberg', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Waldstadion an der Kaiserlinde', 'size' => 1],
                ['name' => 'Greuther Fürth', 'city' => 'Fürth', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Sportpark Ronhof Thomas Sommer', 'size' => 2],
                ['name' => 'Holstein Kiel', 'city' => 'Kiel', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Holstein-Stadion', 'size' => 2],
                ['name' => 'SSV Ulm', 'city' => 'Ulm', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Donaustadion', 'size' => 1],
                ['name' => 'Preußen Münster', 'city' => 'Münster', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Preußenstadion', 'size' => 1],
                ['name' => 'Jahn Regensburg', 'city' => 'Regensburg', 'country' => 'Germany', 'id_league' => 8, 'stadium' => 'Jahnstadion Regensburg', 'size' => 1],

                // 3. Liga (9)
                ['name' => 'Alemannia Aachen', 'city' => 'Aachen', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Tivoli', 'size' => 3],
                ['name' => 'Arminia Bielefeld', 'city' => 'Bielefeld', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Schüco-Arena', 'size' => 4],
                ['name' => 'Energie Cottbus', 'city' => 'Cottbus', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Stadion der Freundschaft', 'size' => 3],
                ['name' => 'Borussia Dortmund II', 'city' => 'Dortmund', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Stadion Rote Erde', 'size' => 2],
                ['name' => 'Dynamo Dresden', 'city' => 'Dresden', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Rudolf-Harbig-Stadion', 'size' => 4],
                ['name' => 'Erzgebirge Aue', 'city' => 'Aue', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Erzgebirgsstadion', 'size' => 3],
                ['name' => 'FC Ingolstadt', 'city' => 'Ingolstadt', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Audi Sportpark', 'size' => 3],
                ['name' => 'Viktoria Köln', 'city' => 'Cologne', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Sportpark Höhenberg', 'size' => 2],
                ['name' => 'Waldhof Mannheim', 'city' => 'Mannheim', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Carl-Benz-Stadion', 'size' => 2],
                ['name' => '1860 Munich', 'city' => 'Munich', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Grünwalder Stadion', 'size' => 3],
                ['name' => 'VfL Osnabrück', 'city' => 'Osnabrück', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Stadion an der Bremer Brücke', 'size' => 3],
                ['name' => 'Hansa Rostock', 'city' => 'Rostock', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Ostseestadion', 'size' => 3],
                ['name' => 'Rot-Weiss Essen', 'city' => 'Essen', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Stadion an der Hafenstraße', 'size' => 3],
                ['name' => 'SV Sandhausen', 'city' => 'Sandhausen', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'GP Stadion am Hardtwald', 'size' => 2],
                ['name' => 'SpVgg Unterhaching', 'city' => 'Unterhaching', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Sportpark Unterhaching', 'size' => 1],
                ['name' => 'VfB Stuttgart II', 'city' => 'Aspach', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'WIRmachenDRUCK Arena', 'size' => 1],
                ['name' => 'SC Verl', 'city' => 'Verl', 'country' => 'Germany', 'id_league' => 9, 'stadium' => 'Sportclub Arena', 'size' => 1],

                // Ligue 1 McDonald’s (10)
                ['name' => 'Paris Saint-Germain', 'city' => 'Paris', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Parc des Princes', 'size' => 5],
                ['name' => 'Olympique Marseille', 'city' => 'Marseille', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Orange Vélodrome', 'size' => 5],
                ['name' => 'AS Monaco', 'city' => 'Monaco', 'country' => 'Monaco', 'id_league' => 10, 'stadium' => 'Stade Louis II', 'size' => 4],
                ['name' => 'Olympique Lyonnais', 'city' => 'Lyon', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Groupama Stadium', 'size' => 4],
                ['name' => 'LOSC Lille', 'city' => 'Lille', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Decathlon Arena Pierre Mauroy', 'size' => 4],
                ['name' => 'OGC Nice', 'city' => 'Nice', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Allianz Riviera', 'size' => 3],
                ['name' => 'RC Lens', 'city' => 'Lens', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade Bollaert‑Delelis', 'size' => 3],
                ['name' => 'Stade Rennais', 'city' => 'Rennes', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Roazhon Park', 'size' => 3],
                ['name' => 'FC Nantes', 'city' => 'Nantes', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade de la Beaujoire', 'size' => 3],
                ['name' => 'Montpellier HSC', 'city' => 'Montpellier', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade de la Mosson', 'size' => 2],
                ['name' => 'Stade Brestois 29', 'city' => 'Brest', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade Francis‑Le Blé', 'size' => 2],
                ['name' => 'Angers SCO', 'city' => 'Angers', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade Raymond Kopa', 'size' => 1],
                ['name' => 'AJ Auxerre', 'city' => 'Auxerre', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade de l’Abbé‑Deschamps', 'size' => 2],
                ['name' => 'Le Havre AC', 'city' => 'Le Havre', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade Océane', 'size' => 2],
                ['name' => 'Stade de Reims', 'city' => 'Reims', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade Auguste Delaune', 'size' => 2],
                ['name' => 'Stade Strasbourg', 'city' => 'Strasbourg', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade de la Meinau', 'size' => 2],
                ['name' => 'AS Saint‑Étienne', 'city' => 'Saint‑Étienne', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stade Geoffroy‑Guichard', 'size' => 3],
                ['name' => 'Toulouse FC', 'city' => 'Toulouse', 'country' => 'France', 'id_league' => 10, 'stadium' => 'Stadium de Toulouse', 'size' => 2],

                // Ligue 2 BKT (11)
                ['name' => 'Le Havre AC', 'city' => 'Le Havre', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Océane', 'size' => 3],
                ['name' => 'AJ Auxerre', 'city' => 'Auxerre', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade de l’Abbé-Deschamps', 'size' => 3],
                ['name' => 'EA Guingamp', 'city' => 'Guingamp', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade de Roudourou', 'size' => 2],
                ['name' => 'Grenoble Foot 38', 'city' => 'Grenoble', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade des Alpes', 'size' => 2],
                ['name' => 'Stade Laval', 'city' => 'Laval', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Francis-Le Basser', 'size' => 1],
                ['name' => 'Valenciennes FC', 'city' => 'Valenciennes', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade du Hainaut', 'size' => 2],
                ['name' => 'Clermont Foot', 'city' => 'Clermont-Ferrand', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Gabriel Montpied', 'size' => 2],
                ['name' => 'Dijon FCO', 'city' => 'Dijon', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Gaston Gérard', 'size' => 2],
                ['name' => 'Nîmes Olympique', 'city' => 'Nîmes', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade des Costières', 'size' => 2],
                ['name' => 'Quevilly Rouen Métropole', 'city' => 'Rouen', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Robert-Diochon', 'size' => 1],
                ['name' => 'Paris FC', 'city' => 'Paris', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Charléty', 'size' => 2],
                ['name' => 'Sochaux', 'city' => 'Montbéliard', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Auguste Bonal', 'size' => 2],
                ['name' => 'AJ Caen', 'city' => 'Caen', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Michel d’Ornano', 'size' => 3],
                ['name' => 'Lorient', 'city' => 'Lorient', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade du Moustoir', 'size' => 3],
                ['name' => 'Troyes AC', 'city' => 'Troyes', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade de l’Aube', 'size' => 2],
                ['name' => 'AC Ajaccio', 'city' => 'Ajaccio', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade François Coty', 'size' => 2],
                ['name' => 'Caen', 'city' => 'Caen', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Michel d’Ornano', 'size' => 3],
                ['name' => 'Paris FC', 'city' => 'Paris', 'country' => 'France', 'id_league' => 11, 'stadium' => 'Stade Charléty', 'size' => 2],

                // Serie A Enilive (12)
                ['name' => 'Juventus', 'city' => 'Turin', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Allianz Stadium', 'size' => 5],
                ['name' => 'AC Milan', 'city' => 'Milan', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'San Siro', 'size' => 5],
                ['name' => 'Inter Milan', 'city' => 'Milan', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'San Siro', 'size' => 5],
                ['name' => 'Napoli', 'city' => 'Naples', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Diego Armando Maradona', 'size' => 4],
                ['name' => 'Roma', 'city' => 'Rome', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Olimpico', 'size' => 4],
                ['name' => 'Lazio', 'city' => 'Rome', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Olimpico', 'size' => 3],
                ['name' => 'Atalanta', 'city' => 'Bergamo', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Gewiss Stadium', 'size' => 3],
                ['name' => 'Fiorentina', 'city' => 'Florence', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Artemio Franchi', 'size' => 3],
                ['name' => 'Sassuolo', 'city' => 'Sassuolo', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Mapei Stadium', 'size' => 2],
                ['name' => 'Torino', 'city' => 'Turin', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Olimpico Grande Torino', 'size' => 3],
                ['name' => 'Udinese', 'city' => 'Udine', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Dacia Arena', 'size' => 2],
                ['name' => 'Monza', 'city' => 'Monza', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Brianteo', 'size' => 2],
                ['name' => 'Empoli', 'city' => 'Empoli', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Carlo Castellani', 'size' => 2],
                ['name' => 'Salernitana', 'city' => 'Salerno', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Arechi', 'size' => 2],
                ['name' => 'Lecce', 'city' => 'Lecce', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Via del Mare', 'size' => 1],
                ['name' => 'Bologna', 'city' => 'Bologna', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Renato Dall’Ara', 'size' => 2],
                ['name' => 'Spezia', 'city' => 'La Spezia', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Alberto Picco', 'size' => 1],
                ['name' => 'Verona', 'city' => 'Verona', 'country' => 'Italy', 'id_league' => 12, 'stadium' => 'Stadio Marcantonio Bentegodi', 'size' => 2],

                // Serie BKT (13)
                ['name' => 'Brescia', 'city' => 'Brescia', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Mario Rigamonti', 'size' => 3],
                ['name' => 'Bari', 'city' => 'Bari', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio San Nicola', 'size' => 3],
                ['name' => 'Palermo', 'city' => 'Palermo', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Renzo Barbera', 'size' => 4],
                ['name' => 'Parma', 'city' => 'Parma', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Ennio Tardini', 'size' => 4],
                ['name' => 'Frosinone', 'city' => 'Frosinone', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Benito Stirpe', 'size' => 3],
                ['name' => 'Cremonese', 'city' => 'Cremona', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Giovanni Zini', 'size' => 2],
                ['name' => 'Lecce', 'city' => 'Lecce', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Via del Mare', 'size' => 3],
                ['name' => 'Como', 'city' => 'Como', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Giuseppe Sinigaglia', 'size' => 2],
                ['name' => 'Modena', 'city' => 'Modena', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Alberto Braglia', 'size' => 2],
                ['name' => 'Cosenza', 'city' => 'Cosenza', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio San Vito-Gigi Marulla', 'size' => 1],
                ['name' => 'Reggina', 'city' => 'Reggio Calabria', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Oreste Granillo', 'size' => 2],
                ['name' => 'Pisa', 'city' => 'Pisa', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Arena Garibaldi – Stadio Romeo Anconetani', 'size' => 2],
                ['name' => 'Cittadella', 'city' => 'Cittadella', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Pier Cesare Tombolato', 'size' => 1],
                ['name' => 'Sudtirol', 'city' => 'Bolzano', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Druso', 'size' => 1],
                ['name' => 'Benevento', 'city' => 'Benevento', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Ciro Vigorito', 'size' => 2],
                ['name' => 'Cremonese', 'city' => 'Cremona', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Giovanni Zini', 'size' => 2],
                ['name' => 'Perugia', 'city' => 'Perugia', 'country' => 'Italy', 'id_league' => 13, 'stadium' => 'Stadio Renato Curi', 'size' => 2],

                // Major League Soccer (14)
                ['name' => 'LA Galaxy', 'city' => 'Los Angeles', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Dignity Health Sports Park', 'size' => 5],
                ['name' => 'Seattle Sounders', 'city' => 'Seattle', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Lumen Field', 'size' => 5],
                ['name' => 'Atlanta United', 'city' => 'Atlanta', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Mercedes-Benz Stadium', 'size' => 4],
                ['name' => 'Toronto FC', 'city' => 'Toronto', 'country' => 'Canada', 'id_league' => 14, 'stadium' => 'BMO Field', 'size' => 4],
                ['name' => 'New York Red Bulls', 'city' => 'Harrison', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Red Bull Arena', 'size' => 4],
                ['name' => 'Portland Timbers', 'city' => 'Portland', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Providence Park', 'size' => 3],
                ['name' => 'Philadelphia Union', 'city' => 'Chester', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Subaru Park', 'size' => 3],
                ['name' => 'FC Cincinnati', 'city' => 'Cincinnati', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'TQL Stadium', 'size' => 2],
                ['name' => 'Sporting Kansas City', 'city' => 'Kansas City', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Children’s Mercy Park', 'size' => 3],
                ['name' => 'Real Salt Lake', 'city' => 'Salt Lake City', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Rio Tinto Stadium', 'size' => 2],
                ['name' => 'Minnesota United', 'city' => 'Saint Paul', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Allianz Field', 'size' => 2],
                ['name' => 'Chicago Fire', 'city' => 'Chicago', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Soldier Field', 'size' => 3],
                ['name' => 'CF Montréal', 'city' => 'Montreal', 'country' => 'Canada', 'id_league' => 14, 'stadium' => 'Stade Saputo', 'size' => 3],
                ['name' => 'Columbus Crew', 'city' => 'Columbus', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Lower.com Field', 'size' => 3],
                ['name' => 'New England Revolution', 'city' => 'Foxborough', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Gillette Stadium', 'size' => 3],
                ['name' => 'Houston Dynamo', 'city' => 'Houston', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Shell Energy Stadium', 'size' => 2],
                ['name' => 'D.C. United', 'city' => 'Washington', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Audi Field', 'size' => 3],
                ['name' => 'Inter Miami', 'city' => 'Miami', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'DRV PNK Stadium', 'size' => 2],
                ['name' => 'Nashville SC', 'city' => 'Nashville', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Geodis Park', 'size' => 2],
                ['name' => 'Austin FC', 'city' => 'Austin', 'country' => 'USA', 'id_league' => 14, 'stadium' => 'Q2 Stadium', 'size' => 2],

                // MLS Next Pro (15)
                ['name' => 'Atlanta United 2', 'city' => 'Atlanta', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'CHAMPS Soccer Stadium', 'size' => 2],
                ['name' => 'Austin FC II', 'city' => 'Austin', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'St. David’s Performance Center', 'size' => 1],
                ['name' => 'Charlotte FC Next Pro', 'city' => 'Charlotte', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Wingate University Soccer Complex', 'size' => 1],
                ['name' => 'Chicago Fire FC II', 'city' => 'Chicago', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'SeatGeek Stadium', 'size' => 2],
                ['name' => 'Colorado Rapids 2', 'city' => 'Commerce City', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Dick’s Sporting Goods Park', 'size' => 2],
                ['name' => 'Columbus Crew 2', 'city' => 'Columbus', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Historic Crew Stadium', 'size' => 2],
                ['name' => 'FC Cincinnati 2', 'city' => 'Cincinnati', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'TQL Stadium', 'size' => 2],
                ['name' => 'Chicago Fire FC II', 'city' => 'Chicago', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'SeatGeek Stadium', 'size' => 2],
                ['name' => 'Houston Dynamo 2', 'city' => 'Houston', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Dynamo Soccer Park', 'size' => 1],
                ['name' => 'Inter Miami CF II', 'city' => 'Fort Lauderdale', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Inter Miami CF Stadium', 'size' => 1],
                ['name' => 'LA Galaxy II', 'city' => 'Carson', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Dignity Health Sports Park', 'size' => 2],
                ['name' => 'MKE Anomaly FC', 'city' => 'Milwaukee', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Engelmann Stadium', 'size' => 1],
                ['name' => 'New England Revolution II', 'city' => 'Foxborough', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Gillette Stadium', 'size' => 2],
                ['name' => 'New York City FC II', 'city' => 'Orangeburg', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Columbia Soccer Stadium', 'size' => 2],
                ['name' => 'Orlando City B', 'city' => 'Orlando', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Osceola Heritage Park', 'size' => 1],
                ['name' => 'Philadelphia Union II', 'city' => 'Chester', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Subaru Park', 'size' => 2],
                ['name' => 'Portland Timbers 2', 'city' => 'Portland', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Merlo Field', 'size' => 2],
                ['name' => 'Real Monarchs', 'city' => 'Sandy', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Zions Bank Stadium', 'size' => 2],
                ['name' => 'Rochester New York FC', 'city' => 'Rochester', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'John L. DiMarco Field', 'size' => 1],
                ['name' => 'Tacoma Defiance', 'city' => 'Tacoma', 'country' => 'USA', 'id_league' => 15, 'stadium' => 'Starfire Sports Stadium', 'size' => 2],

                // Liga Portugal Placard (16)
                ['name' => 'Benfica', 'city' => 'Lisboa', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio da Luz', 'size' => 5],
                ['name' => 'Porto', 'city' => 'Porto', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio do Dragão', 'size' => 5],
                ['name' => 'Sporting CP', 'city' => 'Lisboa', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio José Alvalade', 'size' => 5],
                ['name' => 'Braga', 'city' => 'Braga', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio Municipal de Braga', 'size' => 3],
                ['name' => 'Vitória SC', 'city' => 'Guimarães', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio D. Afonso Henriques', 'size' => 3],
                ['name' => 'Marítimo', 'city' => 'Funchal', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio dos Barreiros', 'size' => 2],
                ['name' => 'Gil Vicente', 'city' => 'Barcelos', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio Cidade de Barcelos', 'size' => 2],
                ['name' => 'Casa Pia', 'city' => 'Lisboa', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio Dr. Magalhães Pessoa', 'size' => 1],
                ['name' => 'Portimonense', 'city' => 'Portimão', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio Municipal de Portimão', 'size' => 2],
                ['name' => 'Paços de Ferreira', 'city' => 'Paços de Ferreira', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio da Capital do Móvel', 'size' => 2],
                ['name' => 'Famalicão', 'city' => 'Vila Nova de Famalicão', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio Municipal de Famalicão', 'size' => 2],
                ['name' => 'Moreirense', 'city' => 'Moreira de Cónegos', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Parque de Jogos Comendador Joaquim de Almeida Freitas', 'size' => 1],
                ['name' => 'Tondela', 'city' => 'Tondela', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio João Cardoso', 'size' => 1],
                ['name' => 'Chaves', 'city' => 'Chaves', 'country' => 'Portugal', 'id_league' => 16, 'stadium' => 'Estádio Municipal de Chaves', 'size' => 1],

                // Pro League (17)
                ['name' => 'Club Brugge', 'city' => 'Bruges', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Jan Breydel Stadium', 'size' => 5],
                ['name' => 'RSC Anderlecht', 'city' => 'Brussels', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Lotto Park', 'size' => 5],
                ['name' => 'Standard Liège', 'city' => 'Liège', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Stade Maurice Dufrasne', 'size' => 4],
                ['name' => 'KAA Gent', 'city' => 'Ghent', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Ghelamco Arena', 'size' => 4],
                ['name' => 'KRC Genk', 'city' => 'Genk', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Cegeka Arena', 'size' => 4],
                ['name' => 'Royal Antwerp', 'city' => 'Antwerp', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Bosuilstadion', 'size' => 3],
                ['name' => 'Sint-Truiden', 'city' => 'Sint-Truiden', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Stayen', 'size' => 2],
                ['name' => 'Cercle Brugge', 'city' => 'Bruges', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Jan Breydel Stadium', 'size' => 2],
                ['name' => 'KV Mechelen', 'city' => 'Mechelen', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'AFAS Stadion', 'size' => 2],
                ['name' => 'Charleroi', 'city' => 'Charleroi', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Stade du Pays de Charleroi', 'size' => 2],
                ['name' => 'OH Leuven', 'city' => 'Leuven', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Den Dreef', 'size' => 1],
                ['name' => 'Seraing', 'city' => 'Seraing', 'country' => 'Belgium', 'id_league' => 17, 'stadium' => 'Stade du Pairay', 'size' => 1],

                // Eredivisie (18)
                ['name' => 'Ajax', 'city' => 'Amsterdam', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Johan Cruijff ArenA', 'size' => 5],
                ['name' => 'PSV Eindhoven', 'city' => 'Eindhoven', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Philips Stadion', 'size' => 5],
                ['name' => 'Feyenoord', 'city' => 'Rotterdam', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'De Kuip', 'size' => 5],
                ['name' => 'AZ Alkmaar', 'city' => 'Alkmaar', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'AFAS Stadion', 'size' => 4],
                ['name' => 'Vitesse', 'city' => 'Arnhem', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'GelreDome', 'size' => 3],
                ['name' => 'FC Utrecht', 'city' => 'Utrecht', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Stadion Galgenwaard', 'size' => 3],
                ['name' => 'SC Heerenveen', 'city' => 'Heerenveen', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Abe Lenstra Stadion', 'size' => 3],
                ['name' => 'Sparta Rotterdam', 'city' => 'Rotterdam', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Het Kasteel', 'size' => 2],
                ['name' => 'Go Ahead Eagles', 'city' => 'Deventer', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'De Adelaarshorst', 'size' => 2],
                ['name' => 'FC Twente', 'city' => 'Enschede', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'De Grolsch Veste', 'size' => 3],
                ['name' => 'Heracles Almelo', 'city' => 'Almelo', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Erve Asito', 'size' => 2],
                ['name' => 'RKC Waalwijk', 'city' => 'Waalwijk', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Mandemakers Stadion', 'size' => 1],
                ['name' => 'PEC Zwolle', 'city' => 'Zwolle', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'MAC³PARK Stadion', 'size' => 2],
                ['name' => 'Fortuna Sittard', 'city' => 'Sittard', 'country' => 'Netherlands', 'id_league' => 18, 'stadium' => 'Fortuna Sittard Stadion', 'size' => 1],

                // Allsvenskan (19)
                ['name' => 'Malmö FF', 'city' => 'Malmö', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Eleda Stadion', 'size' => 5],
                ['name' => 'AIK', 'city' => 'Stockholm', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Friends Arena', 'size' => 4],
                ['name' => 'IFK Göteborg', 'city' => 'Gothenburg', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Gamla Ullevi', 'size' => 4],
                ['name' => 'Djurgårdens IF', 'city' => 'Stockholm', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Tele2 Arena', 'size' => 4],
                ['name' => 'Hammarby IF', 'city' => 'Stockholm', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Tele2 Arena', 'size' => 4],
                ['name' => 'IF Elfsborg', 'city' => 'Borås', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Borås Arena', 'size' => 3],
                ['name' => 'Helsingborgs IF', 'city' => 'Helsingborg', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Olympia', 'size' => 3],
                ['name' => 'Örebro SK', 'city' => 'Örebro', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Behrn Arena', 'size' => 2],
                ['name' => 'Varbergs BoIS', 'city' => 'Varberg', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Påskbergsvallen', 'size' => 2],
                ['name' => 'IFK Norrköping', 'city' => 'Norrköping', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Östgötaporten', 'size' => 3],
                ['name' => 'Kalmar FF', 'city' => 'Kalmar', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Guldfågeln Arena', 'size' => 2],
                ['name' => 'BK Häcken', 'city' => 'Gothenburg', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Bravida Arena', 'size' => 2],
                ['name' => 'Degerfors IF', 'city' => 'Degerfors', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'Stora Valla', 'size' => 1],
                ['name' => 'GIF Sundsvall', 'city' => 'Sundsvall', 'country' => 'Sweden', 'id_league' => 19, 'stadium' => 'NP3 Arena', 'size' => 1],

                // Süper Lig (20)
                ['name' => 'Galatasaray', 'city' => 'Istanbul', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Nef Stadium', 'size' => 5],
                ['name' => 'Fenerbahçe', 'city' => 'Istanbul', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Şükrü Saracoğlu Stadium', 'size' => 5],
                ['name' => 'Beşiktaş', 'city' => 'Istanbul', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Vodafone Park', 'size' => 5],
                ['name' => 'Trabzonspor', 'city' => 'Trabzon', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Şenol Güneş Stadium', 'size' => 4],
                ['name' => 'İstanbul Başakşehir', 'city' => 'Istanbul', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Başakşehir Fatih Terim Stadium', 'size' => 3],
                ['name' => 'Konyaspor', 'city' => 'Konya', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Konya Büyükşehir Stadium', 'size' => 2],
                ['name' => 'Sivasspor', 'city' => 'Sivas', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Sivas 4 Eylül Stadium', 'size' => 2],
                ['name' => 'Gaziantep FK', 'city' => 'Gaziantep', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Gaziantep Stadium', 'size' => 2],
                ['name' => 'Çaykur Rizespor', 'city' => 'Rize', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Çaykur Didi Stadium', 'size' => 1],
                ['name' => 'Alanyaspor', 'city' => 'Alanya', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Bahçeşehir Okulları Stadium', 'size' => 2],
                ['name' => 'Giresunspor', 'city' => 'Giresun', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Çotanak Sports Complex', 'size' => 1],
                ['name' => 'Kayserispor', 'city' => 'Kayseri', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Kadir Has Stadium', 'size' => 2],
                ['name' => 'Antalyaspor', 'city' => 'Antalya', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Antalya Stadium', 'size' => 2],
                ['name' => 'Fatih Karagümrük', 'city' => 'Istanbul', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Atatürk Olympic Stadium', 'size' => 1],
                ['name' => 'Kasımpaşa', 'city' => 'Istanbul', 'country' => 'Turkey', 'id_league' => 20, 'stadium' => 'Kasımpaşa Recep Tayyip Erdoğan Stadium', 'size' => 1],

                // Brasileirão A
                ['name' => 'Flamengo', 'city' => 'Rio de Janeiro', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Maracanã', 'size' => 5],
                ['name' => 'Palmeiras', 'city' => 'São Paulo', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Allianz Parque', 'size' => 5],
                ['name' => 'São Paulo', 'city' => 'São Paulo', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Morumbi', 'size' => 5],
                ['name' => 'Corinthians', 'city' => 'São Paulo', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Neo Química Arena', 'size' => 5],
                ['name' => 'Fluminense', 'city' => 'Rio de Janeiro', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Maracanã', 'size' => 4],
                ['name' => 'Botafogo', 'city' => 'Rio de Janeiro', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Nilton Santos', 'size' => 4],
                ['name' => 'Cruzeiro', 'city' => 'Belo Horizonte', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Mineirão', 'size' => 4],
                ['name' => 'Atlético Mineiro', 'city' => 'Belo Horizonte', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Arena MRV', 'size' => 4],
                ['name' => 'Internacional', 'city' => 'Porto Alegre', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Beira-Rio', 'size' => 4],
                ['name' => 'Grêmio', 'city' => 'Porto Alegre', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Arena do Grêmio', 'size' => 4],
                ['name' => 'Vasco da Gama', 'city' => 'Rio de Janeiro', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'São Januário', 'size' => 3],
                ['name' => 'Bahia', 'city' => 'Salvador', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Fonte Nova', 'size' => 3],
                ['name' => 'Fortaleza', 'city' => 'Fortaleza', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Castelão', 'size' => 3],
                ['name' => 'Ceará', 'city' => 'Fortaleza', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Castelão', 'size' => 2],
                ['name' => 'Sport Recife', 'city' => 'Recife', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Ilha do Retiro', 'size' => 2],
                ['name' => 'Juventude', 'city' => 'Caxias do Sul', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Alfredo Jaconi', 'size' => 2],
                ['name' => 'Mirassol', 'city' => 'Mirassol', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Fields Maia', 'size' => 1],
                ['name' => 'Santos', 'city' => 'Santos', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Vila Belmiro', 'size' => 4],
                ['name' => 'Red Bull Bragantino', 'city' => 'Bragança Paulista', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Nabi Abi Chedid', 'size' => 3],
                ['name' => 'Vitória', 'city' => 'Salvador', 'country' => 'Brazil', 'id_league' => 21, 'stadium' => 'Barradão', 'size' => 1],

                // Brasileirão B
                ['name' => 'Amazonas', 'city' => 'Manaus', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Arena da Amazônia', 'size' => 2],
                ['name' => 'América Mineiro', 'city' => 'Belo Horizonte', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Independência', 'size' => 3],
                ['name' => 'Athletic Club (MG)', 'city' => 'São João del Rei', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Campo das Alterosas', 'size' => 1],
                ['name' => 'Atlético Goianiense', 'city' => 'Goiânia', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Antônio Accioly', 'size' => 3],
                ['name' => 'Athletico Paranaense', 'city' => 'Curitiba', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Arena da Baixada', 'size' => 4],
                ['name' => 'Avaí', 'city' => 'Florianópolis', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Ressacada', 'size' => 3],
                ['name' => 'Botafogo-SP', 'city' => 'Ribeirão Preto', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Santa Cruz', 'size' => 2],
                ['name' => 'Chapecoense', 'city' => 'Chapecó', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Arena Condá', 'size' => 2],
                ['name' => 'Coritiba', 'city' => 'Curitiba', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Couto Pereira', 'size' => 3],
                ['name' => 'Criciúma', 'city' => 'Criciúma', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Heriberto Hülse', 'size' => 2],
                ['name' => 'Cuiabá', 'city' => 'Cuiabá', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Arena Pantanal', 'size' => 3],
                ['name' => 'CRB', 'city' => 'Maceió', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Rei Pelé', 'size' => 2],
                ['name' => 'Ferroviária', 'city' => 'Araraquara', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Fonte Luminosa', 'size' => 2],
                ['name' => 'Goiás', 'city' => 'Goiânia', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Serrinha', 'size' => 3],
                ['name' => 'Novorizontino', 'city' => 'Novo Horizonte', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Jorge Ismael de Biasi', 'size' => 2],
                ['name' => 'Operário-PR', 'city' => 'Ponta Grossa', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Germano Krüger', 'size' => 2],
                ['name' => 'Paysandu', 'city' => 'Belém', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Curuzu', 'size' => 2],
                ['name' => 'Remo', 'city' => 'Belém', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Mangueirão', 'size' => 2],
                ['name' => 'Vila Nova', 'city' => 'Goiânia', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Onésio Brasileiro Alvarenga', 'size' => 2],
                ['name' => 'Volta Redonda', 'city' => 'Volta Redonda', 'country' => 'Brazil', 'id_league' => 22, 'stadium' => 'Estádio Raulino de Oliveira', 'size' => 2],

                // Brasileirão C
                ['name' => 'ABC', 'city' => 'Natal', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Frasqueirão', 'size' => 3],
                ['name' => 'Anápolis', 'city' => 'Anápolis', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Jonas Duarte', 'size' => 1],
                ['name' => 'Botafogo‑PB', 'city' => 'João Pessoa', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Almeidão', 'size' => 3],
                ['name' => 'Brusque', 'city' => 'Brusque', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Augusto Bauer', 'size' => 2],
                ['name' => 'Caxias', 'city' => 'Caxias do Sul', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Centenário', 'size' => 2],
                ['name' => 'Confiança', 'city' => 'Aracaju', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Batistão', 'size' => 2],
                ['name' => 'CSA', 'city' => 'Maceió', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Rei Pelé', 'size' => 3],
                ['name' => 'Figueirense', 'city' => 'Florianópolis', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Orlando Scarpelli', 'size' => 3],
                ['name' => 'Floresta', 'city' => 'Fortaleza', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Presidente Vargas', 'size' => 1],
                ['name' => 'Guarani', 'city' => 'Campinas', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Brinco de Ouro', 'size' => 3],
                ['name' => 'Itabaiana', 'city' => 'Itabaiana', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Etelvino Mendonça', 'size' => 1],
                ['name' => 'Ituano', 'city' => 'Itu', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Novelli Júnior', 'size' => 2],
                ['name' => 'Londrina', 'city' => 'Londrina', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Estádio do Café', 'size' => 3],
                ['name' => 'Maringá', 'city' => 'Maringá', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Willie Davids', 'size' => 1],
                ['name' => 'Náutico', 'city' => 'Recife', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Dos Aflitos', 'size' => 3],
                ['name' => 'Ponte Preta', 'city' => 'Campinas', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Moisés Lucarelli', 'size' => 3],
                ['name' => 'Retrô', 'city' => 'Camaragibe', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Arena Pernambuco', 'size' => 1],
                ['name' => 'São Bernardo', 'city' => 'São Bernardo do Campo', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => '1º de Maio', 'size' => 1],
                ['name' => 'Tombense', 'city' => 'Tombos', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Almeidão', 'size' => 2],
                ['name' => 'Ypiranga‑RS', 'city' => 'Erechim', 'country' => 'Brazil', 'id_league' => 23, 'stadium' => 'Colosso da Lagoa', 'size' => 2],
            ]
        );
    }
}
